### ISSUE TITLE
Upload limit not enforced

### ISSUE THREAD

**Issue by maxxer** [coova/coova-chilli#10]
Upload bandwidth limit is not working from 1.2.9 version up.
In 1.2.8 and previous versions it worked properly, but since 1.2.9 is not working any more.
In 1.3.0 (latest SVN as well) this problem still exists. 

Detailed info here:
http://www.linkedin.com/groups/wisprbandwidthmaxup-limit-not-working-in-158903.S.267802350

**Comment by obsy** [comment]
@ynezz: could you show your settings? Because my upload is not working, coova 1.2.8- 1.3.1-svn, on BB 14.07 and own build.

**Comment by sevan** [comment]
@maxxer is this still an issue with the latest version from git?

**Comment by maxxer** [comment]
@sevan sadly I haven't had a chance to test it lately
