### ISSUE TITLE
Covachilli connectivity issue with radius server

### ISSUE THREAD

**Issue by shankarsh15** [coova/coova-chilli#102]
Hi ,

I am using DLink Router DIR 505 and using openwrt as firmware and installed Covachilli on it.
I am using radius server for authentication.

I am able to successfully authenticate with radius server from my home network and get internet.
But when I am installing the same router at my office network, it just gets stuck at the login page saying "Please wait".

Can someone please help in figuring out what could be the possible issue.

I also tried to access the radius logs to check if I am seeing my office IP details but there are none.

Appreciate someone`s help in this regard.

Thanks
Shankar

**Comment by sevan** [comment]
Ignoring coova, from the dlink router running openwrt, are you able to authenticate against the radius server using a radius client?

**Comment by sevan** [comment]
Hi,
There is now [a mailing list for questions such as these](https://www.brightonchilli.org.uk/mailman/listinfo/coovachilli), the issues section will be used solely for bug reports in code from now on, can I ask you to subscribe & take the discussion there (give it a few days as the system is freshly setup without any subscribers at the moment).
