### ISSUE TITLE
macallowed option

### ISSUE THREAD

**Issue by adrienb4** [coova/coova-chilli#103]
Hi

I just discovered 'macallowed' option have a limit to 16 mac in embedded. I can change this limit without causing any problems in Coova ? 

What is the conditions (hardware) for use in embedded ? I have compiled Coova for Netgear WNR3500Lv1 and Asus RT-AC56U. 

Thank for responses

**Comment by wlanmac** [comment]
You should be safe to increase the limit in chilli_limits.h

**Comment by adrienb4** [comment]
What is the hardware spec for use '--enable-largelimits' ?

I use a soekris motherboard (http://soekris.eu/shop/net6501/net6501_50_board_only_en.html) and with  this option i have a segfault :
```
kernel: [10549.424473] chilli[16233]: segfault at 46 ip b74092e7 sp bfa4bae0 error 4 in libc-2.11.3.so[b73ae000+140000]
```

@wlanmac : Sorry but  i dont understand what do you mean. I can modify the limit or not ?

Thank 

Adrien

**Comment by QuentinH85** [comment]
Hi,
I was just issuing the same issue and correcting it at the moment:
You need to recompile Coova, after editing the file /src/chilli_limits.h
You can see MACOK_MAX is set to 16 by default. If you compile with the option --enable-largelimits, you get this parameter to 56 (check a few lines upper).

So you can:
*Compile with  --enable-largelimits and see if your system support it. (All the changes implied are detail in the same file). If this cause the kernel error you mention, then no.
*or edit the 16 to any number of your choice and compile.

Cordially, Quentin.

**Comment by ajanta2689** [comment]
Hi,

I tried increasing the MACOK_MAX in src/chilli_limits.h file, but inside config, HS_MACALLOW option supports number of MAC only till 156.
Is there any limitation with the length of command line argument ?
Need help, urgent !!

Thanks in advance
Ajanta
