### ISSUE TITLE
Why NASID isn't in the json responses ?

### ISSUE THREAD

**Issue by irongomme** [coova/coova-chilli#111]
Or I can turn the question in another way : 

How can we know the NAS where we are sending a request ?

I'm a little desapointed about it because when user is disconnected, i've got the location information in the status json request. But when user is connected, I lose this information, and my only option is to find him in RADACCT table with its username and sessionID .... !

But, the easiest way would be to have the NASID returned in each status request. Isn't it ?

**Comment by wlanmac** [comment]
No specific reason... feel free to submit a pull request. thanks!
