### ISSUE TITLE
CoovaChilli layer3 IP problem.

### ISSUE THREAD

**Issue by ObaidAshraf** [coova/coova-chilli#114]
Hello all.
I am trying to setup coovachilli with layer3 in fedora. But, when i put "HS_LAYER3=on", the client doesn't get the IP address. I read that with layer3, coova shuts-off its internal DHCP and clients gets IP Address via external DHCP server. I used "dhcpd" of fedora, but after enabling dhcpd, clients gets IP but can't get to coova login page.
Plz help !!
Here is the config file.
HS_WANIF=em1           # WAN Interface toward the Internet
HS_LANIF=wlan0		   # Subscriber Interface for client devices
HS_NETWORK=10.20.30.0	   # HotSpot Network (must include HS_UAMLISTEN)
HS_NETMASK=255.255.255.0   # HotSpot Network Netmask
HS_UAMLISTEN=10.20.30.1	   # HotSpot IP Address (on subscriber network)
HS_UAMPORT=3990            # HotSpot UAM Port (on subscriber network)
HS_UAMUIPORT=4990          # HotSpot UAM "UI" Port (on subscriber network, for embedded portal)

HS_DYNIP=10.20.30.10
HS_DYNIP_MASK=255.255.255.0
HS_STATIP=10.20.30.2
HS_STATIP_MASK=255.255.255.0

HS_DNS1=10.20.30.1
HS_DNS2=192.168.30.1

HS_NASID=nas01
HS_RADIUS=192.168.30.34
HS_RADIUS2=192.168.30.34
HS_UAMALLOW=www.coova.org
HS_RADSECRET=testing123    # Set to be your RADIUS shared secret
HS_UAMSECRET=uamsecret     # Set to be your UAM secret
HS_UAMALIASNAME=chilli

HS_ANYIP=on		   # Allow any IP address on subscriber LAN
HS_MODE=hotspot
HS_TYPE=coovachilli
HS_WWWDIR=/usr/local/etc/chilli/www
HS_WWWBIN=/usr/local/etc/chilli/wwwsh
HS_PROVIDER=Coova
HS_PROVIDER_LINK=http://coova.github.io/
HS_LOC_NAME="My HotSpot"	   # WISPr Location Name and used in portal
HS_LAYER3=on

**Comment by wlanmac** [comment]
What is your DHCPd config? Be sure that it is servicing the tun/tap interface...

**Comment by ObaidAshraf** [comment]
thanks wlanmac for replying.
My dhcpd config is:

subnet 192.168.10.0 netmask 255.255.255.0 {        
      range 192.168.10.200 192.168.10.225;
        option subnet-mask 255.255.255.0;
        option domain-name-servers 192.168.10.1,8.8.8.8,8.8.4.4;
        option routers 192.168.10.1;
}

subnet 10.1.0.0 netmask 255.255.255.0 {
        range 10.1.0.200 10.1.0.225;
        option subnet-mask 255.255.255.0;
        option domain-name-servers 10.1.0.1,8.8.8.8,8.8.4.4;
        option routers 10.1.0.1;
}

I tried to run dhcpd on "tun0" but it is not servicing the tun0 interface. I read that dhcpd can't service tun interface :( ..

**Comment by wlanmac** [comment]
Use the --tap option...

**Comment by ObaidAshraf** [comment]
I overcame the previous problem by using DHCPRELAYAGENT. 
But now i am into different problem, i have privoxy configured at the same host on which i've configured and running coovachilli. I am trying to forward traffic from coova tun interface (tun0) to the address which privoxy is listening (in my case 127.0.0.1:8118). I tried both iptables (http://coova.github.io/mail-archive/chilli/2012-May/001959.html) and POSTAUTHPROXY feature of coovachilli but no luck..
Please help about this issue :( ..

**Comment by ObaidAshraf** [comment]
Issue resolved.
Closing the issue.

**Comment by tomasell** [comment]
@ObaidAshraf Can you post your configuration? Maybe i've the same problem, i cannot fix it.
Thanks!
