### ISSUE TITLE
About versioning

### ISSUE THREAD

**Issue by muratbeser** [coova/coova-chilli#172]
Hi, 
Why not tagging the versions ?

**Comment by skotos** [comment]
I've noticed that 1.3.1.3 is now tagged.  Is coova-chilli now following a 4 segment version system, or should I interpret this as 1.3.1-r3?  The reason behind my question is that I am trying to fix up the gentoo ebuilds, and need to know how versions will work going forward, as this will impact upgrade paths.

**Comment by Spomky** [comment]
IMHO, you should follow the [Semantic Versioning Specification](http://semver.org/).
There are only 3 segments. Alpha, Beta or RC version can be easily tagged using this specification.

**Comment by pinkra** [comment]
Hi all! Yes, i agree with Semantic Versioning Specification. Actually the last 3 should be interpreted as r3..

**Comment by muratbeser** [comment]
Also I'm agreed with  Semantic Versioning @skotos  Coova had so many patch since 1.3.0,
There is a milestone for 1.3.2 but it's not published

**Comment by skotos** [comment]
I'm wondering if we could keep tagging to the Semantic version going forward.  So for 1a1bc23 instead of a git tag 1.3.1.3 we use git tag v1.3.1-r3. (or should it be v1.3.1-p3)

**Comment by pinkra** [comment]
Yes, i put there a milestone (1.3.2) because we must serve a new milestone for users as a reference..  has been passed a long time since the last coova chilli milestone and much code has developed.

**Comment by muratbeser** [comment]
Which means we have decide a version and milestones.
