### ISSUE TITLE
coova dhcp option 43

### ISSUE THREAD

**Issue by adrienb4** [coova/coova-chilli#193]
Hi

I would like to say if it's possible to use/implement option 43 in the dhcp of Coova. 
I want to resolve a dns name from the stations.

See this link (option 43 block)

https://help.ubnt.com/hc/en-us/articles/204909754-UniFi-Layer-3-methods-for-UAP-adoption-and-management

Adrien

**Comment by gbaligh** [comment]
Hi,

Can you try the coova-chilli configuration argument : 
```--dhcpopt <hex-encoded-binary-dhcp-option>```

**Comment by adrienb4** [comment]
Sorry but I dont understand what do you mean with <hex-encoded-binary-dhcp-option>.

**Comment by gbaligh** [comment]
You can compile coova-chilli whith [--enable-dhcpopt](https://github.com/coova/coova-chilli/blob/master/configure.ac#L264) to activate the DHCP option setting.

To add a DHCP option, you can use the [--dhcpopt](https://github.com/coova/coova-chilli/blob/master/src/cmdline.ggo#L280) command argument or the [HS_DHCPOPT](https://github.com/coova/coova-chilli/blob/master/conf/functions.in#L147) configuration parameter.

I don't know if this can feet your need ?

**Comment by adrienb4** [comment]
The dhcpopt is activate in my coova-chilli.
I want to set the controler to my Unifi AP with the option 43.

I have set the option with this value :

```
dhcpopt                           010452762e0
```

**Comment by gbaligh** [comment]
I think that you have to provide all options field : 

>From RFC2132:
Code   Len   Vendor-specific information
   +-----+-----+-----+-----+---
   |  43 |  n  |  i1 |  i2 | ...
   +-----+-----+-----+-----+---

So in you case it must start with 2B04.

**Comment by adrienb4** [comment]
Sorry but even with your help it is not working. My Coova is compiled with --enable-dhcpopt and configured with 
```
dhcpopt                           0104052762e0
```

I cant display dhcp options with wireshark, 43 is not in the list.

**Comment by gbaligh** [comment]
you can not see option 43, because there is no 43 in your hex string.
can you try `dhcpopt 2B04052762e0` ?

**Comment by adrienb4** [comment]
It's not necessary to set the vendor ID ?

**Comment by gbaligh** [comment]
Sorry, it surpass my knowledge :)
You can check the [RFC](https://www.ietf.org/rfc/rfc2132.txt) at `8.4. Vendor Specific Information`
All I know, is that all options must start with `option number` and `length`.

**Comment by gbaligh** [comment]
If I'm not mistaking, this is what I understand : 
Assuming that the IPv4 address, to encode into the vendor-extension code `1`, is `201.10.7.31`
`dhcpopt` must contains `2B070104C90A071FFF`

**Comment by adrienb4** [comment]
Yes it's exactly that (you're faster than me to answer) :P
In all the documentation I found, the '2B07' is deducted.

https://help.ubnt.com/hc/en-us/articles/204909754-UniFi-Layer-3-methods-for-UAP-adoption-and-management#Section_4

```
Cisco CLI

# assuming your UniFi is at 192.168.3.10
ip dhcp pool <pool name>
network <ip network> <netmask>
default-router <default-router IP address>
dns-server <dns server IP address>
option 43 hex 0104C0A8030A # 192.168.3.10 -> CO A8 03 0A

# Why 0104C0A8030A ?
#
# 01: suboption
# 04: length of the payload (must be 4)
# C0A8030A: 192.168.3.10
```

It is this block that I understand everything.

Thank for your help @gbaligh now my Unifi AP are directly connected to my controler without change the URL informer :P
