### ISSUE TITLE
Add custom attribute value pair in Access-Request packet?

### ISSUE THREAD

**Issue by lin-lu** [coova/coova-chilli#198]
Hi all,

This is what I receive in the FreeRADIUS debug output.
```
(0) Received Access-Request Id 11 from 127.0.0.1:39883 to 127.0.0.1:1812 length 272
(0)   ChilliSpot-Version = "1.3.0"
(0)   User-Name = "alice"
(0)   User-Password = "passme"
(0)   Service-Type = Login-User
(0)   Acct-Session-Id = "5698fa7500000001"
(0)   Framed-IP-Address = 172.21.16.2
(0)   NAS-Port-Type = Wireless-802.11
(0)   NAS-Port = 1
(0)   NAS-Port-Id = "00000001"
(0)   Calling-Station-Id = "84-7A-88-6D-2D-D8"
(0)   Called-Station-Id = "34-02-86-A5-C6-93"
(0)   NAS-IP-Address = 172.21.16.1
(0)   NAS-Identifier = "nas01"
(0)   WISPr-Location-ID = "isocc=,cc=,ac=,network=Coova,"
(0)   WISPr-Location-Name = "My_HotSpot"
(0)   WISPr-Logoff-URL = "http://172.21.16.1:3990/logoff"
(0)   Message-Authenticator = 0x718bddfe5d1c66215a622447b4470540

```
My question is: can I add some custom attributes with chilli? For instance: Custom-Attribute = "SomeValue".

**Comment by sevan** [comment]
Hi,
There is now [a mailing list for questions such as these](https://www.brightonchilli.org.uk/mailman/listinfo/coovachilli), the issues section will be used solely for bug reports in code from now on, can I ask you to subscribe & take the discussion there (give it a few days as the system is freshly setup without any subscribers at the moment).
