### ISSUE TITLE
Transfer mac to the site

### ISSUE THREAD

**Issue by xADMx** [coova/coova-chilli#199]
Prompt please as it is possible to send a user mac-address to the website???

**Comment by sevan** [comment]
Hi,
There is now [a mailing list for questions such as these](https://www.brightonchilli.org.uk/mailman/listinfo/coovachilli), the issues section will be used solely for bug reports in code from now on, can I ask you to subscribe & take the discussion there (give it a few days as the system is freshly setup without any subscribers at the moment).
