### ISSUE TITLE
Too many HTTP requests are redirected to the web server.

### ISSUE THREAD

**Issue by lin-lu** [coova/coova-chilli#205]
Hi all,

I know that CoovaChilli will redirect the user to the portal login page if the user is not authorized and tries to open an HTTP site in the browser.

However, when a Windows laptop is connected and it will automatically send many Windows Update HTTP requests , and CoovaChilli redirects all these requests to my web server, this is causing the max client error on the web server.

My question is: is there a way to configure CoovaChilli, so that it will ignore some HTTP requests that are sent to a certain destination IP?

Lin

**Comment by sevan** [comment]
Is whitelisting using the `uamallowed` option feasible?

**Comment by gareth41** [comment]
Use a JavaScript redirect, most won't follow this kind of redirect. Windows update eg will follow a 302 but not a parent.location.replace

**Comment by muratbeser** [comment]
Coova handles all requests not only HTTP, so its not responsibility of Coova but your web server. 
Also there is other specific software which send requests to the internet check their updates etc stuff.

**Comment by sevan** [comment]
Hi,
There is now [a mailing list for questions such as these](https://www.brightonchilli.org.uk/mailman/listinfo/coovachilli), the issues section will be used solely for bug reports in code from now on, can I ask you to subscribe & take the discussion there (give it a few days as the system is freshly setup without any subscribers at the moment).
