### ISSUE TITLE
Question: unathorized users access some particular services???

### ISSUE THREAD

**Issue by joseacosta** [coova/coova-chilli#208]
There is a way to allow unauthorized users to access secured pages.????

ie. unauthorized users can access https pages freely (port 443) but they will redirected on regular pages.????

In other words, could **unauthorized** users be allowed to use some particular ports/services, even before they aunthenticate???

**Comment by rokco** [comment]
maybe option uamallowed is what you are looking for? see man page http://coova.github.io/CoovaChilli/chilli.conf%285%29.html

**Comment by joseacosta** [comment]
Thank you rokco, i have made some research before asking here.

I have tired hard to use UAMALLOWED and UAMDOMAINS to do that, and no success.

UAMALLOWED is very specific, theres no such thing as "allow all destinations on port 443"

i have tried UAMALLOWED with values as _*.com:443 or any:443,_ with not success

Even some general domain as _paypal.com:443_ didn`t worked
where **very especifics domains** like _www.paypal.com:443_  **DOES** work.

Besides, i have tried those "wildcard" values on UAMDOMAINS and none of them worked :(

There is a way to allow all "https" destinations, no mather what domain it is?

**Comment by rokco** [comment]
looking at the manual page, there is no possibility to have wildcards in uamallowed.
just a guess: try using 0.0.0.0:443
if that does not work use option uamregex

**Comment by joseacosta** [comment]
Great, rocko i find out by myself shortly after i wrote my question but, you nailed it, it works!.

0.0.0.0:443

I hope your answer helps somebody else.

Now... it would be great if we could "disalow" some particular domains, maybe this is too permissive, maybe uamregex?
but ... im happy wit this solution for now.

Thank You rocko
