### ISSUE TITLE
Question: openssl version

### ISSUE THREAD

**Issue by rokco** [coova/coova-chilli#209]
Hi there!
I once flashed CoovaAP Firmware - version 1.0 beta.12 on Linksys WRTG54 and its running fine since. Now I would like to upgrade due to security reasons (still openssl 0.9.8). It seems there are no complete router firmware images offered anymore right? Would the latest build ship a newer openssl version or does this depend on the underlying operating system? 
thanks

**Comment by sevan** [comment]
CoovaChilli does not ship with OpenSSL but links to the OpenSSL library provided by the host OS.

By the way, there is now [a mailing list for questions such as these](https://www.brightonchilli.org.uk/mailman/listinfo/coovachilli), the issues section will be used solely for bug reports in code from now on.
