### ISSUE TITLE
Question: enable ssl over uamport

### ISSUE THREAD

**Issue by tomasell** [coova/coova-chilli#213]
How can i enable ssl over uamport, so i can use json api over https?
Thanks!

**Comment by irongomme** [comment]
Hi, I'm facing the same problem.

@tomasell , do you have found something about this ?

**Comment by nemesisdesign** [comment]
Issue closed without reply. Thank you man!

**Comment by nemesisdesign** [comment]
I opened another issue for this question, I hope we'll be able to figure out an answer: https://github.com/coova/coova-chilli/issues/461
