### ISSUE TITLE
DNS filtering does not work

### ISSUE THREAD

**Issue by miguelangel-nubla** [coova/coova-chilli#214]
As I understand you should not be able to make DNS queries before login, unless the domain is specified in `uamdomains`, but I am able query `dig bing.com @<uamlisten>` and get an answer.

I guess the default here https://github.com/coova/coova-chilli/blob/master/src/dns.c#L435 should be return -1 (error)?

Anyone experiencing similar issues?

**Comment by wlanmac** [comment]
DNS has to work before login, otherwise users wouldn't get redirected (they would time out on DNS). The uamdomain options allows walled garden access to those domains (so... the user can browse those domains before logging in).

**Comment by miguelangel-nubla** [comment]
Yes, that is what I mean. I have not added the domain bing.com to uamdomain, and the query is still resolving the IP correctly.
It should just not resolve that domain.

**Comment by nzamps** [comment]
All domains resolve you just can’t access them before login in any other way e.g. via http unless in uamdomain, uamallowed etc.

-
brian

**Comment by miguelangel-nubla** [comment]
Is that the expected behavior?
Then what is the purpose of this filtering https://github.com/coova/coova-chilli/blob/master/src/dns.c#L214-L253?

**Comment by nzamps** [comment]
That’s the expected behaviour.
That chunk of code sets *qmatch = 1 which is used later on to add the A record to the walled-garden.

-
brian
