### ISSUE TITLE
RFC7710 Support

### ISSUE THREAD

**Issue by Spomky** [coova/coova-chilli#215]
Does coova-chilli support the [RFC7710](https://tools.ietf.org/html/rfc7710)?

**Comment by wlanmac** [comment]
Indeed, support for RFC 7710 is planned, but it isn't clear yet how client vendors will implement the feature. The RFC provides a mechanism to inform the client of configuration (e.g. the captive portal URL), but it lacks the ability to inform the client of state (are they being held captive currently or not). So, the value for the client to get configuration only is limited... (the client still needs to do a captive portal detection to derive state). Now, combined with [ICMP for state notification](https://tools.ietf.org/html/draft-wkumari-capport-icmp-unreach-00), I think we have something!

**Comment by Spomky** [comment]
Close as PR #274 has been created
