### ISSUE TITLE
Milestone 1.3.2

### ISSUE THREAD

**Issue by pinkra** [coova/coova-chilli#217]
I think we have to set this milestone to have a clear reference for all using coova-chilli. Can we create it with the actual code or have we to solve other major features/bug prior to create it?

**Comment by muratbeser** [comment]
Hey thanks for bringing front this issue with more elegant title :) 
Here's my offer; 

I think first document what we have this documentation could lead us to the specifications, then we could decide which spec we should support or not support. 

Bugs are already what we have in our hands, so they do not have any effect on major feature map.

**Comment by Spomky** [comment]
Hi,

Is there any news concerning the next stable release of this project?
I am preparing a PR to update the OpenWRT package, but I prefer to wait for a new tag instead of creating a package based on a dev version.

Regards.

**Comment by sevan** [comment]
Many apologies, I ended up cutting a new release without realising a version number had been designated.  v1.3.1.4 is born

**Comment by pinkra** [comment]
Good.. next 1.3.2 ?

**Comment by sevan** [comment]
Sure

**Comment by sevan** [comment]
we reached 1.3.2 :)
