### ISSUE TITLE
Question Trying to login from a ionic app

### ISSUE THREAD

**Issue by greemlin** [coova/coova-chilli#218]
Hello, I hope I am in the right spot for my question.
I am trying for a month now to successfully login to a chilli hotspot using an ionic application (I need to make a mobile app which will login t chilli so the client can surf the internet).
I am using the Chilli library, i ve set the port and url of the chilliController in my script (see below).
I can logoff sucessfully (when I have logged in throught the web page), but when I am trying to login via javascript chillicontroller.logon(username, password) I get an error: challenge not found. Please help!!!
 ... I thought the host will handle the username and password so it is hashed properly...

what I did is:
chilliController.host = "172.50.70.1";
chilliController.port = "3990";
chilliController.logon( username , password ) ;

as described here: http://blog.trifork.com/2013/01/15/building-a-captive-portal-controlling-access-to-the-internet-from-your-network/

Any help or push to the right direction would be really appreciated..

**Comment by muratbeser** [comment]
you could use https://github.com/mpangrazzi/pepper instead of default.

**Comment by greemlin** [comment]
Thank you very much for your reply

Sincerely, Nick Kap
