### ISSUE TITLE
Call external login page

### ISSUE THREAD

**Issue by mazzy89** [coova/coova-chilli#22]
Due to the poor documentation, it is pretty hard figure out how to make work coova chilli controller. I don't understand some variables in the config file. I would like to address the user to a login page located to an external server but I don't understand this variables and how to use them.

```bash
HS_UAMSERVER

HS_UAMFORMAT

HS_UAMHOMEPAGE

HS_UAMSERVICE
```

HS_UAMSERVER should be the variable which point to the address so should be an IP address but I don't know how to use correctly the above remaining variables. Which is the difference between the second and third variable? and what is HS_UAMSERVICE? The config file suggests to read this link http://www.coova.org/CoovaChilli/UAMService but it is down

**Comment by wlanmac** [comment]
All you really need is HS_UAMFORMAT

**Comment by sjbeskur** [comment]
We typically us both  HS_UAMSERVER and HS_UAMFORMAT once upon a time I think there was an issue if UAMSERVER was not specified.  example:

HS_UAMSERVER=mydomain.com

# really nothing to be done here 
HS_UAMFORMAT=https://\$HS_UAMSERVER

Also be sure to set your set your radius servers, secrets , nasid's etc.

**Comment by sevan** [comment]
@mazzy89 still stuck or can this ticket be closed?

**Comment by mazzy89** [comment]
yes the issue can be closed
