### ISSUE TITLE
Mini-Portal Windows 8.1 / Chrome (Login)

### ISSUE THREAD

**Issue by ausfeldj** [coova/coova-chilli#229]
So the problem appears to be Windows or my laptop.  I am running hostapd (ac) + chilli + radius without any trouble on a physical ubuntu 14.04 machine.  Everything is up to date or compiled from source.  IOS, and OSX machines work great, same for Linux.  I have not tried Andriod yet.  The problem seems to be isolated to windows 8.1 Pro or my dell xps laptop as it does not connect to the wifi access point on any default web browser and the mini-portal is not displayed.  The message simply times out saying cannot connect to the network.  There was some internet chatter about Chrome presenting problems but Firefox works just fine.  Neither work for me on this machine.  Has anybody run into this situation and how did you resolve it?  Any help, advice would be very much appreciated.

UPDATE:

Narrowed this down.  On all windows machines 8.1 and 10 you cannot have a both a WPA key AND Chilli running.  All other OS's tested did not have this problem.  It's not a popup, ad blocker, defender, firewall problem.  I also did not see any difference in tos vs self on the miniportal settings in windows.  It's a long story why I wanted to have both enabled in the first place.  I am probably going to have to go with chilli only.

I was going to try to give free internet for a while, say 5 seconds, that will assign an IP address etc. and then a redirect the users to see if that makes any difference.  Does anybody know how to do that?

**Comment by sevan** [comment]
Hi,
There is now [a mailing list for questions such as these](https://www.brightonchilli.org.uk/mailman/listinfo/coovachilli), the issues section will be used solely for bug reports in code from now on, can I ask you to subscribe & take the discussion there (give it a few days as the system is freshly setup without any subscribers at the moment).
