### ISSUE TITLE
Radius Vendor Attributes are prefixed with ChilliSpot rather than coovachilli

### ISSUE THREAD

**Issue by ageekymonk** [coova/coova-chilli#23]
While i was trying to use Radius Vendor specific Attributes, the attribute names are all prefixed with "chillispot" rather than coovachilli. 

Is it good to change them to be consistent with the project name ?

**Comment by wlanmac** [comment]
Yes, I suppose it's time... originally, they were kept ChilliSpot for backward compatibility.

**Comment by alex-eri** [comment]
But some attributes not compatibile with ChilliSpot and has different meaning.
