### ISSUE TITLE
Google DNS

### ISSUE THREAD

**Issue by irongomme** [coova/coova-chilli#230]
Hi there,

I'm facing a little problem with coova set with google dns, and android captive portal detection.

I need to add google-analytics in uamdomain to track users statistics. But, by opening google-analytics, i'm also opening the same ip pool that is used by the captive portal detection mechanism in android systems. 

I've tried to change google DNS by another one, but this doesnt work for every android devices, depending on android version and the url used by captive portal detection.

Thus my question is : what can i do to solve this issue ?

I could use google analytics server side, but i'd rather use a smarter solution ... any ideas ?

**Comment by sevan** [comment]
Hi,
There is now [a mailing list for questions such as these](https://www.brightonchilli.org.uk/mailman/listinfo/coovachilli), the issues section will be used solely for bug reports in code from now on, can I ask you to subscribe & take the discussion there (give it a few days as the system is freshly setup without any subscribers at the moment).
