### ISSUE TITLE
radius dhcp server + chilli not working correct

### ISSUE THREAD

**Issue by hasanesfahan** [coova/coova-chilli#235]
We want to config Freeradius (version 3.0.10) to use it as a DHCP server. It works fine, when the Chilli service is stopped.
If I run the Chilli with layer3=on, the scenario will failed and the clients can't get IP address from Freeradius. 
If I run the Chilli with layer3=off, the scenario will work fine, except for DNS servers. In this case, the Chilli fills it's DNS server's IP to DHCP response and my client will take Chilli's DNS servers IP as it's own DNS.
How I can solve both problems?

Thanks.

**Comment by sevan** [comment]
Hi,
There is now [a mailing list for questions such as these](https://www.brightonchilli.org.uk/mailman/listinfo/coovachilli), the issues section will be used solely for bug reports in code from now on, can I ask you to subscribe & take the discussion there (give it a few days as the system is freshly setup without any subscribers at the moment).
