### ISSUE TITLE
Session Not Getting Through Once Authenticated via Radius

### ISSUE THREAD

**Issue by jnedila** [coova/coova-chilli#238]
Coova Chilli 1.3.0
External captive portal with external Radius server

Client device connects to SSID, receives an IP, is redirected to external web server.
Login happens via external server callback to Coova Chilli, and a Radius request and Access-Accept is received by Coova Chilli.

Debug logs show the Access-Accept is received, and the client device is redirected to the post auth URL.
However, Coova Chilli is intercepting this last HTTP request and sending the device back to the login page. 

Any idea why Coova Chilli didn't open a session up for this device, even though a Radius Access-Accept was received?

Debug logs:

redir.c: 2103: 0 (Debug) The path: logon
redir.c: 1903: 0 (Debug) The parameter username is: [AVQv_zVQ3oMr1yW9XZtT]
redir.c: 2267: 0 (Debug) -->> Setting username=[AVQv_zVQ3oMr1yW9XZtT]
redir.c: 1903: 0 (Debug) The parameter userurl is: [http://www.example.com?SESSID=95mfnoa55bm5gqv2gq7veqt9u3&LANG=en]
redir.c: 2273: 0 (Debug) -->> Setting userurl=[http://www.example.com?SESSID=95mfnoa55bm5gqv2gq7veqt9u3&LANG=en]
redir.c: 2295: 0 (Debug) using uamprotocol: WISPr 1.0 (1)
redir.c: 1903: 0 (Debug) The parameter response is: [299e0e2fcfa0a67fd6e5418fc1274916]
redir.c: 3794: 0 (Debug) redir_accept: Sending RADIUS request
radius.c: 1315: 0 (Debug) RADIUS client 0.0.0.0:0
redir.c: 2642: 0 (Debug) created radius packet (code=1, id=4, len=33)

redir.c: 2803: 0 (Debug) sending radius packet (code=1, id=4, len=308)

radius.c: 321: 0 (Debug) Allocating RADIUS packet
radius.c: 1898: 0 (Debug) Received RADIUS packet id=4
radius.c: 421: 0 (Debug) Freeing RADIUS packet
radius.c: 426: 0 (Debug) RADIUS queue-out id=4 idx=0
redir.c: 2431: 0 (Debug) Received RADIUS response
redir.c: 2474: 0 (Debug) +attribute Class (41 bytes): 415651765f7a5651336f4d7231795739585a74543b56616e636f757665722054617869204775657374
redir.c: 2531: 0 (Debug) +attribute EAP msg (0 bytes): 
redir.c: 3818: 0 (Debug) redir_main handling Access-Accept
redir.c: 777: 0 (Debug) redir_wispr1_reply
chilli.c: 5840: 0 (Debug) UAM login with unknown IP address: 10.1.0.2
redir.c: 3854: 0 (Debug) -->> Msg userurl=[http://www.example.com?SESSID=95mfnoa55bm5gqv2gq7veqt9u3&LANG=en]

chilli.c: 379: 0 (Debug) caught 17 via selfpipe
chilli.c: 310: 0 (Debug) child 5391 terminated
chilli.c: 135: 0 (Debug) Freed child process 5391 [[redir]]
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: www.examplei.com
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: www.examplei.com
dns.c: 187: 0 (Debug) It was a dns record type: 5 class: 1
dns.c: 336: 0 (Debug) CNAME record www.example.com.
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
redir.c: 2103: 0 (Debug) The path: 
redir.c: 2413: 0 (Debug) -->> Setting userurl=[http://www.example.com/?SESSID=95mfnoa55bm5gqv2gq7veqt9u3&LANG=en]
redir.c: 3962: 0 (Debug) redir_accept: Original request host=www.example.com
redir.c: 4071: 0 (Debug) ---->>> resetting challenge: 1ee439509258b8e3a1bab52f37a0ee56
chilli.c: 5840: 0 (Debug) UAM login with unknown IP address: 10.1.0.2
redir.c: 987: 0 (Debug) redir_wispr2_reply
chilli.c: 379: 0 (Debug) caught 17 via selfpipe
chilli.c: 310: 0 (Debug) child 5392 terminated
chilli.c: 135: 0 (Debug) Freed child process 5392 [[redir]]

**Comment by sevan** [comment]
Hi,
Can you try the latest release & report your findings on the mailing list, there is now [a mailing list for questions such as these](https://www.brightonchilli.org.uk/mailman/listinfo/coovachilli), the issues section will be used solely for bug reports in code from now on (give it a few days as the system is freshly setup without any subscribers at the moment).
