### ISSUE TITLE
CoovaChilli

### ISSUE THREAD

**Issue by josealgardataborges** [coova/coova-chilli#240]
How on earth i make the browser open the UAM upon the user connecting to the wireless network?

1. User turns on WIFI on the smartphone (android/ios)
2. User selects correct WIFI SSID
3. User taps LOGIN to connect to WIFI
4. ... Chilli/FreeRadius/Chilli do their stuff ...
5. Browser open with the UAM url in it
6. User can then type his username/password to access internet.

I'm only missing step 5... The browser wont open... :(

I use this **HS_REDIRDNSREQ=on** on /etc/chilli/config, but sometimes it works sometimes it doesnt.

Any advise?

**Comment by josealgardataborges** [comment]
Here's my /etc/chilli/config

# -*- mode: shell-script; -*-
#
#   Coova-Chilli Default Grase Configurations.
#   To customize, copy this file to @ETCCHILLI@/config
#   and edit to your liking. This is included in shell scripts
#   that configure chilli and related programs before file 'config'.
### Get dynamic vars from Grase Hotspot
GRASE_VARS=$(cat /etc/dnsmasq.d/01-grasehotspot | grep \#)
HS_NETWORK=$(echo "$GRASE_VARS" |grep chilli_network|awk '{print $2}');
HS_NETMASK=$(echo "$GRASE_VARS" |grep chilli_netmask|awk '{print $2}');
HS_UAMLISTEN=$(echo "$GRASE_VARS" |grep chilli_lanip|awk '{print $2}');
HS_WANIF=$(echo "$GRASE_VARS" |grep chilli_wanif|awk '{print $2}');
HS_LANIF=$(echo "$GRASE_VARS" |grep chilli_lanif|awk '{print $2}');
HS_REDIRDNSREQ=on
HS_WANIF=${HS_WANIF:-eth0}
HS_LANIF=${HS_LANIF:-eth1}
HS_NETWORK=${HS_NETWORK:-10.1.0.0}
HS_NETMASK=${HS_NETMASK:-255.255.255.0}
HS_UAMLISTEN=${HS_UAMLISTEN:-10.1.0.1}
HS_UAMPORT=3990
HS_UAMUIPORT=4990
HS_DNS_DOMAIN=hotspot.lan
HS_DNS1=$HS_UAMLISTEN
HS_DNS2=$HS_UAMLISTEN
HS_MAXCLIENTS=65000
HS_NASID=nas01
HS_RADIUS=localhost
HS_RADIUS2=localhost
HS_UAMALLOW=$HS_UAMLISTEN
HS_RADSECRET=SuperSpecialSecret 
HS_UAMALIASNAME=grase
HS_UAMDOMAINS=".google-analytics.com,.googletagmanager.com,.gstatic.com,.googleapis.com"
HS_UAMSERVER=$HS_UAMLISTEN
HS_UAMFORMAT=http://\$HS_UAMSERVER/grase/uam/hotspot
HS_UAMHOMEPAGE=http://\$HS_UAMSERVER/grase/uam/hotspot
HS_MACAUTH=on	
HS_TCP_PORTS="80 443 22 2812 53 3990 3128"
HS_MODE=hotspot
HS_TYPE=chillispot
HS_ADMUSR=CoovaChilli
HS_ADMPWD=radmin
HS_DEFINTERIMINTERVAL=150
HS_WWWDIR=/etc/chilli/www
HS_WWWBIN=/etc/chilli/wwwsh
HS_PROVIDER=Grase
HS_PROVIDER_LINK=http://hotspot.purewhite.id.au/
HS_LOC_NAME="GRASE HotSpot"

**Comment by sevan** [comment]
Hi,
There is now [a mailing list for questions such as these](https://www.brightonchilli.org.uk/mailman/listinfo/coovachilli), the issues section will be used solely for bug reports in code from now on, can I ask you to subscribe & take the discussion there (give it a few days as the system is freshly setup without any subscribers at the moment).

**Comment by josealgardataborges** [comment]
@sevan ok thanks...
