### ISSUE TITLE
Coova ARP

### ISSUE THREAD

**Issue by Bargee** [coova/coova-chilli#241]
Hi. Does anyone know how to clear the ARP cache of Coove-chilli? I am accessing Coova via multiple entry points which are WiFi repeaters. Accessing from a different repeater results in Coova debug showing 'Received packet with spoofed source!'. I'm thinking that by clearing the ARP cache that this will then update with the clients new entry.

**Comment by sevan** [comment]
Hi,
There is now [a mailing list for questions such as these](https://www.brightonchilli.org.uk/mailman/listinfo/coovachilli), the issues section will be used solely for bug reports in code from now on, can I ask you to subscribe & take the discussion there (give it a few days as the system is freshly setup without any subscribers at the moment).
