### ISSUE TITLE
How to configure coova-chili

### ISSUE THREAD

**Issue by pascalrem** [coova/coova-chilli#243]
Hi

Can you help me for a correct installation. I will install a HOTSPOT GUEST.

I will create 2 VLANS : 
- VLAN 1 for the internal use in my company with all access. IP adresse : 10.50.200.x
- VLAN 5 for the guest under WIFI with just access for internet,mail and tchat. IP adresse : 10.50.210.x. Don't see the other network (VLAN 1).

See the attach file

It's possible this configuration. And how can I do that.

Thanks
[PROJET HOTSPOT.pdf](https://github.com/coova/coova-chilli/files/269786/PROJET.HOTSPOT.pdf)

**Comment by sevan** [comment]
Hi,
There is now [a mailing list for questions such as these](https://www.brightonchilli.org.uk/mailman/listinfo/coovachilli), the issues section will be used solely for bug reports in code from now on, can I ask you to subscribe & take the discussion there (give it a few days as the system is freshly setup without any subscribers at the moment).
