### ISSUE TITLE
'bin/sh: can't open '/etc/rc.common

### ISSUE THREAD

**Issue by Spomky** [coova/coova-chilli#244]
Hi,

I have the following error message that occured just after the installation of coova-chilli on my OpenWRT router (self compiled package): `'bin/sh: can't open '/etc/rc.common`
This error occures again when I try to start the chilli service: `/etc/init.d/chilli start`

As far as I undersand, this error comes from a bad end of line encoding (windows instead of unix EOL).
It can be verify by editing the file:

```
#!/bin/sh /etc/rc.common^M
^M
START=30^M
STOP=90^M
...
```

Is it possible to verify that all the files of this project use a correct EOL encoding and fix them if needed?

Thanks

**Comment by sevan** [comment]
This should be taken care of automatically [on new commits](https://github.com/coova/coova-chilli/blob/master/.gitattributes)
When you say self compiled package, you mean you checked out this repo & built it?

**Comment by Spomky** [comment]
You are right. The problem was due to a text editor I used for a quick modification of a file and not the project itself. It is fixed now.
I compiled the package using the OpenWRT buildroot and a [modified package configuration](https://github.com/Wi-Ho/packages/tree/master/net/coova-chilli).

Besides, when do you plan to release the v1.3.2? It seems the [milestone is completed](https://github.com/coova/coova-chilli/milestones/1.3.2) but no tag has been added.
When done, I think I will create a PR to update the OpenWRT package (BTW I need feedback).

**Comment by sevan** [comment]
I've cut a new release but missed the intended v1.3.2 tag. Apologies.

**Comment by Spomky** [comment]
OK thanks. I have just submitted a PR onto OpenWRT packages repository that takes into account this new release plus some configuration options (see https://github.com/openwrt/packages/pull/2737).
Feel free to comment it if you noted something is wrong.

Regards.
