### ISSUE TITLE
Coova+Social login issue

### ISSUE THREAD

**Issue by Benelli86** [coova/coova-chilli#247]
Hi all.
I have same problem with coova and login via social.
I need to enter the domains of the social (e.g. facebook) in uamdomain to allow facebook login, but so the client can navigate without authentication on facebook!!
Can we help me?

**Comment by sevan** [comment]
Hi,
There is now [a mailing list for questions such as these](https://www.brightonchilli.org.uk/mailman/listinfo/coovachilli), the issues section will be used solely for bug reports in code from now on, can I ask you to subscribe & take the discussion there (give it a few days as the system is freshly setup without any subscribers at the moment).
