### ISSUE TITLE
Documentation about xt_coova/ipt-coova/nfcoova

### ISSUE THREAD

**Issue by pparent76** [coova/coova-chilli#248]
Hi,

I'm lacking documentation on how to have chili working with xt_coova.

I compiled it with  --with-nfcoova option, i have the xt_coova linux module running, and I don't observe any improvement on performances, or CPU usage.

Also lsmod shows that the module xt_coova is not called:
[...]
xt_connlimit            3296  0 
xt_connmark              960  3 
xt_conntrack            2064 14 
xt_coova                5312  0 
xt_dscp                  928  0 
xt_ecn                  1216  0 
xt_helper                800  0 
xt_hl                    720  0 
xt_id                    400  0 
[...]

I guess, I must be missing something, but I don't find any documentation on how to setup xt-coova. Is there a special option to set in the config file, or special iptables to setup?

Thanks in advance!
Pierre.

**Comment by sevan** [comment]
Hi,
There is now [a mailing list for questions such as these](https://www.brightonchilli.org.uk/mailman/listinfo/coovachilli), the issues section will be used solely for bug reports in code from now on, can I ask you to subscribe & take the discussion there (give it a few days as the system is freshly setup without any subscribers at the moment).
