### ISSUE TITLE
Coova cuts upload on GBit NIC?!!!

### ISSUE THREAD

**Issue by skoubri** [coova/coova-chilli#256]
Hi to all, having coovachilli 1.3.0 x64 with radiusdesk packages have noticed that every client who is connected on 100Mbit link speed is ok an can take up to 100Mbit upload & download speeds... BUT if any windows client is connected through GBit NIC, download is ok (full speed).. but Upload speed is from zero to some Kbps!!!! Even a file on Google Drive cannot be uploaded!! System Ubuntu 14.04LTS 4GB RAM Xeon processor and two GBit Intel Pro Desktop adapters... Many thanks in advance!

**Comment by rexy74** [comment]
Hi, i've written about the same behaviour at the end of the previous issue (#255)

**Comment by nzamps** [comment]
Sounds like you need to disable gso and tso:

ethtool -K eth0 gso off gro off tso off

where eth0 is your WAN.

-
Brian

**Comment by skoubri** [comment]
MANY MANY THANKS!!!!!!!!!!!!!!!! applied the command but on eth1 (LAN)... solved the problem!!!!!!!!!!!


RESPECT!!

**Comment by knumat** [comment]
For those that might run across this issue in the future, the idea of setting "gro off" was originally proposed in #32 .  A bit more information about the affected kernel versions can be found in that issue.
