### ISSUE TITLE
Coova-chilli and proxy sever

### ISSUE THREAD

**Issue by thanhminh30** [coova/coova-chilli#258]
Hi, Is anyone here setup coovachilli with proxy sever success?
i try use HS_POSTAUTH_PROXY 127.0.0.1 or 10.0.0.1 ,it not work, add iptables in ipup.sh 
iptables -t nat -I PREROUTING -p tcp -i $TUNTAP -d 10.1.0.1 --dport 80 -j REDIRECT --to-ports 8080,
but tinyproxy still don't show anything in log, what i'm missing?

Thanks in advance.

**Comment by nzamps** [comment]
Yeah, we use it…our FW rules are more like this:

iptables -I INPUT -i tun0 -p tcp -m tcp --dport 8080 --dst 10.1.0.1 -j ACCEPT
iptables -I INPUT -i tun0 -p tcp -m tcp --dport 80 --dst 10.1.0.1 -j ACCEPT

iptables -A PREROUTING -t mangle -p tcp -s 10.1.0.0/24 -d 10.1.0.1 --dport 8080 -j DROP
iptables -A PREROUTING -t nat -i tun0 -p tcp -s 10.1.0.0/24 ! -d 10.1.0.1 --dport 80 -j REDIRECT --to 8080

Also make sure your tinyproxy config has:

Allow 10.1.0.0/24

Adjust the above to match your setup.

-
brian

**Comment by thanhminh30** [comment]
I go back to ver 1.3, and it work, i don't know why, may be when install ver 1.3.1.4, i forgot --enable something.
