### ISSUE TITLE
Chilli not works with TomatoUSB mips (cross-compile)

### ISSUE THREAD

**Issue by MrDini123** [coova/coova-chilli#259]
Hi!

I compiled a chilli binary with the openwrt toolchain and I created an ipk for entware-ng. After it, I installed it, but when I try to start it, it gives me an error:

```
root@TomatoUSB:/# chilli -c /opt/etc/chilli.conf
chilli: can't resolve symbol '__res_state' in lib 'chilli'.
```

What's wrong?

Thanks!

**Comment by gbaligh** [comment]
Hi,

The problem is not related to coovachilli, you need to use the exact same toolchains as used to generate your target.
