### ISSUE TITLE
Ubuntu 16.04 Could Not Generate Configuration File

### ISSUE THREAD

**Issue by dwipujono** [coova/coova-chilli#263]
Hi,

I try coovachilli 1.3.1.4 on Ubuntu 16.04, but it genere an error when I run chilli --debug --fg.

> root@ChilliTest:/etc/chilli#` chilli --debug --fg
> coova-chilli[1575]: (Re)processing options [/var/run/chilli.1575.cfg.bin]
> coova-chilli[1576]: running chilli_opt on /var/run/chilli.1575.cfg.bin
> coova-chilli: Error opening configuration file '/etc/chilli/main.conf'
> coova-chilli: Error opening configuration file '/etc/chilli/hs.conf'
> coova-chilli: Error opening configuration file '/etc/chilli/local.conf'
> coova-chilli[1575]: could not generate configuration (/var/run/chilli.1575.cfg.bin), sleeping one second
> coova-chilli[1575]: (Re)processing options [/var/run/chilli.1575.cfg.bin]
> coova-chilli[1577]: running chilli_opt on /var/run/chilli.1575.cfg.bin
> coova-chilli: Error opening configuration file '/etc/chilli/main.conf'
> coova-chilli: Error opening configuration file '/etc/chilli/hs.conf'
> coova-chilli: Error opening configuration file '/etc/chilli/local.conf'
> coova-chilli[1575]: could not generate configuration (/var/run/chilli.1575.cfg.bin), sleeping one second
> coova-chilli[1575]: (Re)processing options [/var/run/chilli.1575.cfg.bin]
> coova-chilli[1578]: running chilli_opt on /var/run/chilli.1575.cfg.bin
> coova-chilli: Error opening configuration file '/etc/chilli/main.conf'
> coova-chilli: Error opening configuration file '/etc/chilli/hs.conf'
> coova-chilli: Error opening configuration file '/etc/chilli/local.conf'
> coova-chilli[1575]: could not generate configuration (/var/run/chilli.1575.cfg.bin), sleeping one second
> coova-chilli[1575]: PID 1575 reloaded binary options file

Please assist.

Thank you.
Pujo

**Comment by mfaroukg** [comment]
same here!

**Comment by vsidou** [comment]
Did you build coovachilli 1.3.1.4 yourself ? or used packaged deb files ?

Normally if you built the code using ./configure --prefix=/usr it should work fine.

Have you checked wether /etc/default/chilli is activated ? 
Also you can use : 

>  /etc/init.d/chilli radconfig

in order to generate config file before trying to run coovachilli

**Comment by dwipujono** [comment]
Hi,

I build from the source with 
`./configure --prefix=`
So it is installed in /etc/chilli/

There is no file named chilli in /etc/default/
I try to run /etc/init.d/chilli radconfig but it encounters an error:

> /etc/init.d/chilli: 9: .: Can't open /etc/rc.d/init.d/functions

**Comment by vsidou** [comment]
You need to build it with : 

> ./configure --prefix=/usr
Then

> make

> sudo make  install

Make sure /etc/chilli contains files
Make also sure /etc/chilli.conf does exist
Then activated chilli in /etc/default/chilli
Generate configuration using ;

> /etc/init.d/chilli radconfig

Then try again

**Comment by dwipujono** [comment]
Hi vsidou,

I have tried your solution, but it encounters same error.
Any suggestion?

Regards,
Pujo

**Comment by Spomky** [comment]
Hi,

I still have the same error.
Just for information, the package is built from the OpenWRT package with its default configuration.

**Comment by muratbeser** [comment]
Hi, could u guys check permissions ? 
what I see in here it's a permission issue.

**Comment by hailIulius** [comment]
Hi,

Looking on the /etc/chilli.conf 

cat /etc/chilli.conf 

include /etc/chilli/main.conf
include /etc/chilli/hs.conf
include /etc/chilli/local.conf

ipup=/etc/chilli/up.sh
ipdown=/etc/chilli/down.sh


But the there are no such files in  /etc/chilli/

ls -all  /etc/chilli/
total 68
drwxr-xr-x   3 root   root    4096 Sep 12 13:53 .
drwxr-xr-x 139 root   root   12288 Sep 12 13:53 ..
-rw-r--r--   1 root   root    6619 Sep 12 13:46 defaults
-rwsr-x---   1 root   chilli   611 Sep 12 13:46 down.sh
-rwxr-xr-x   1 root   root   13707 Sep 12 13:46 functions
-rw-r--r--   1 root   root     687 Sep 12 13:46 gui-config-default.ini
-rwxr-xr-x   1 root   root     567 Sep 12 13:46 newmulti.sh
-rwsr-x---   1 root   chilli  2879 Sep 12 13:46 up.sh
-rwxr-xr-x   1 root   root    1896 Sep 12 13:46 wpad.dat
drwxr-xr-x   2 chilli root    4096 Sep 12 13:53 www
-rwxr-xr-x   1 root   root    1025 Sep 12 13:46 wwwsh

**Comment by github-jeff** [comment]
same problem.  Any solutions?

**Comment by hailIulius** [comment]
sudo cp /etc/chilli/defaults /etc/chilli/conf
/etc/init.d/chilli start - will generate main.conf,hs.conf,local.conf

**Comment by github-jeff** [comment]
Thank you for the suggesttion hailulius.  Unfortunately

sudo cp /etc/chilli/defaults /etc/chilli/conf
or
sudo cp /etc/chilli/defaults /etc/chilli/config  - This is what it says in the default file header

cp defaults to conf or cp defaults to config (as it states in the defaults file) does not work.

/usr/etc/init.d# chilli start
coova-chilli[7368]: (Re)processing options [/usr/var/run/chilli.7368.cfg.bin]
coova-chilli[7369]: running chilli_opt on /usr/var/run/chilli.7368.cfg.bin
coova-chilli: Error opening configuration file '/usr/etc/chilli/main.conf'
coova-chilli: Error opening configuration file '/usr/etc/chilli/hs.conf'
coova-chilli: Error opening configuration file '/usr/etc/chilli/local.conf'

**Comment by sevan** [comment]
try `chilli -fd`

**Comment by github-jeff** [comment]
Now I can see what's going on.  Thank you.

Looks like it is resolving the requests well enough but it is not allowing
any access to the users.
