### ISSUE TITLE
Logon using ChilliLibrary.js returns clientstate = 0

### ISSUE THREAD

**Issue by mcsanantonio** [coova/coova-chilli#264]
Hi, 

I hope you can assist me with my problem.
I have setup an external server for my login page for coovachilli.
$HS_UAMSERVER = mydomain.com

The ChilliLibrary.js is included and the my script is as follows:

```
$('#login-form').on('submit', function(e){
        e.stopPropagation();
        e.preventDefault();
        
        var username = $('#username').val();
        var password = $('#password').val();
        
       chilliController.logon(username, password);
});
```

But I cannot connect and I am receiving this response:

```

chilliJSON: JSON reply received in 1018 ms
    version = 1.0
    clientState = 0
    challenge = 279c839ec5ea451b963da5d25c09fb24
    redir = [object Object]
      originalURL = http://go.microsoft.com/fwlink/?LinkID=219472&clcid=0x409
      redirectionURL = 
      logoutURL = http://192.168.10.1:3990/logoff
      ipAddress = 192.168.10.6
      macAddress = 40-F0-2F-0A-9F-8C
```

Is there anything that I am missing? 

Thanks

**Comment by vsidou** [comment]
Hi,

Are you using a radius as auth server ?
Have you tried to logon using tested username and password on the remote radius ? 

Take a look at logonStep2 function in ChilliLibrary. As you would see it uses 2 methods (depending if you activated or not UAMSERVICE)

Also take a look at the chilliController.js code. It's a good example on how to setup (or integrate it) on your framework.

**Comment by mcsanantonio** [comment]
Hi,

Yes I am using Radius as my auth server and I can login using the added account.
I didn't active my UAMSERVICE yet as I am testing logging in using CHAP password.

I will take a look. 

Thank Vsidou.

**Comment by cheseremtitus24** [comment]
this article might shed light
https://sourceforge.net/p/hotcakes/wiki/Coova%20Chilli%20JSON%20Interface/
