### ISSUE TITLE
Can`t decode User-Password raduis attribute while PAP auth

### ISSUE THREAD

**Issue by alex-eri** [coova/coova-chilli#287]
Radius server tested with mikrotik and radtest.  User-Password decoded with pw-decrypt has wrong data - random bytes.

Trying to login with:
http://192.168.182.1:3990/logon?username=000010&password=972668

i.e. without chap. Chap is not needed because of OTP from external UAM page.

**Comment by alex-eri** [comment]
I found that PAP password is XORed with challenge. Is there any way to use Plain Plaintext passwords.

**Comment by tranvanhoa533** [comment]
Hi @alex-eri,

I also encountered this problem. Can you share how to solve it?
