### ISSUE TITLE
sslkeypass not working

### ISSUE THREAD

**Issue by miglio** [coova/coova-chilli#297]
The private key passphrase is not working. 
Looking into the ssl.c file I edited the following function:

````
#ifdef HAVE_OPENSSL

static int _openssl_passwd(char *buf, int size, int rwflag, void *ud) {
  strlcpy(buf, _options.sslkeypass, size);
  memset(_options.sslkeypass,'x',strlen(_options.sslkeypass));
  return 0;
}
#endif
````

and modified the return code to **strlen(buf)**. now it works.

The wiki for openssl say: 

> The pem_passwd_cb(), which must be provided by the application, hands back the password to be used during decryption. On invocation a pointer to userdata is provided. The pem_passwd_cb must write the password into the provided buffer buf which is of size size. **The actual length of the password must be returned to the calling function**. rwflag indicates whether the callback is used for reading/decryption (rwflag=0) or writing/encryption (rwflag=1).

Source: [https://wiki.openssl.org/index.php/Manual:SSL_CTX_set_default_passwd_cb(3)](url)

**Comment by gbaligh** [comment]
That's 💯 % correct 😄 !
