### ISSUE TITLE
OpenWrt Json not working

### ISSUE THREAD

**Issue by xewonder** [coova/coova-chilli#314]
Hi,
I am trying to fix my issue  #294 but seem to be having problems compiling json?

I have applied the diff in the post above , and everything seems to compile correctly, but when i test with http://10.1.0.1:3990/json/status, it just pushes me back to the spash page! Obviously json is not working.

Could someone please help me with this as I am not very sure what I'm doing!

I attach the log of the compile of coova-chilli for Openwrt 14.07

Thank you
[coovacompile.txt](https://github.com/coova/coova-chilli/files/636442/coovacompile.txt)

**Comment by xewonder** [comment]
...answering myself, but without having a clue, the log says:

OpenWrt-libtool: install: warning: `libchilli.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: warning: `/home/denisd/14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/coova-chilli-1.3.2/bstring/libbstring.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: warning: `/home/denisd/14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/coova-chilli-1.3.2/json/libjson.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: warning: `../bstring/libbstring.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: warning: `../json/libjson.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: /usr/bin/install -c .libs/chilli /home/denisd/14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/coova-chilli-1.3.2/ipkg-install/usr/sbin/chilli
OpenWrt-libtool: install: warning: `libchilli.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: warning: `/home/denisd/14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/coova-chilli-1.3.2/bstring/libbstring.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: warning: `/home/denisd/14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/coova-chilli-1.3.2/json/libjson.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: warning: `../bstring/libbstring.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: warning: `../json/libjson.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: /usr/bin/install -c .libs/chilli_response /home/denisd/14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/coova-chilli-1.3.2/ipkg-install/usr/sbin/chilli_response
OpenWrt-libtool: install: warning: `libchilli.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: warning: `/home/denisd/14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/coova-chilli-1.3.2/bstring/libbstring.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: warning: `/home/denisd/14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/coova-chilli-1.3.2/json/libjson.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: warning: `../bstring/libbstring.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: warning: `../json/libjson.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: /usr/bin/install -c .libs/chilli_radconfig /home/denisd/14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/coova-chilli-1.3.2/ipkg-install/usr/sbin/chilli_radconfig
OpenWrt-libtool: install: warning: `libchilli.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: warning: `/home/denisd/14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/coova-chilli-1.3.2/bstring/libbstring.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: warning: `/home/denisd/14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/coova-chilli-1.3.2/json/libjson.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: warning: `../bstring/libbstring.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: warning: `../json/libjson.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: /usr/bin/install -c .libs/chilli_opt /home/denisd/14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/coova-chilli-1.3.2/ipkg-install/usr/sbin/chilli_opt
OpenWrt-libtool: install: warning: `libchilli.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: warning: `/home/denisd/14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/coova-chilli-1.3.2/bstring/libbstring.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: warning: `/home/denisd/14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/coova-chilli-1.3.2/json/libjson.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: warning: `../bstring/libbstring.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: warning: `../json/libjson.la' has not been installed in `/usr/lib'
OpenWrt-libtool: install: /usr/bin/install -c .libs/chilli_query /home/denisd/14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/coova-chilli-1.3.2/ipkg-install/usr/sbin/chilli_query

Why would that be?

**Comment by sevan** [comment]
1) Fetch & unzip https://github.com/coova/coova-chilli/releases/tag/1.3.2

2) Run the following:
`sh bootstrap`

`./configure --enable-miniportal --enable-libjson --prefix=/tmp/foo`

`make`

`make install`

3) If all that works, run `/tmp/foo/sbin/chilli -fd` & try visiting 
http://10.1.0.1:3990/json/status

The configuration file for this instance will be in /tmp/foo/etc, by the way.

Do you still have the same issue with the new instance?

**Comment by xewonder** [comment]
@sevan 

I am really sorry.. just learning all this stuff!

where do I unzip? how will it know to build for my chipset?

Sorry and thank you...

**Comment by sevan** [comment]
I was suggesting ignoring the build infrastructure you were using & building manually as a starting point.
If you're cross compiling to another target, that's still possible to do manually by hand but a little more involved.
Ideally you'd have a test env where you can build and run to start with, this reduces the number of components at play.
In a generic sense, one needs to be able to rule out the following independently:
Is it something they're doing wrong?
Is the distro adding gratuitous change which is causing a fallout?
Is the build mechanism being utilised doing something unaccounted for?
Is there a bug in the code base?

**Comment by xewonder** [comment]
Gosh! Thank you  @sevan ...

I am not sure I am the right person to check this... I am not so advanced..

Anyone else out therre building on OpenWrt and able to follow this???

**Comment by pinkra** [comment]
I haven't retry it recently but json support was broken some commits ago..

**Comment by xewonder** [comment]
Thank you.. can someone pleasw help me to get it "up and running" again?

**Comment by sevan** [comment]
@pinkra was that after 0695ac2725faabce28decca37a51e958b0de7051, which updated libjson last year?

**Comment by gbaligh** [comment]
Hi @xewonder,

According to the attached file, containing compilation log : I don't see any problem, you have some warning, that's right, but without harm !
That said, I wont to know, if possible, what's the OpenWRT version you are using ? You are compiling with uClibc witch is replaced by musl in the last version !
I addition, can we have a look into the patch applied for coova-chilli that you added ?
Finally, it will be easier to analyse if you can provide the syslog of coova-chilli, so can you provide us coova-chilli traces when it's running with full debug ?

**Comment by xewonder** [comment]
Hi all and than you for the assistance.

OpenWRT 14.07
Looking at the  build_dir it's uClibc (target-mipsel_24kec+dsp_uClibc-0.9.33.2)

I also attach the patch file.

[203-fix-json-compile.patch.txt](https://github.com/coova/coova-chilli/files/638730/203-fix-json-compile.patch.txt)


The problem is json not working. I attach the  chilli log.

When I call http://192.168.182.1:3990/json/status, I simply get redirected back to the splash page. This explains why  #294 is happening.


chilli[14920]: dhcp_receive_ip(3794): Address found
chilli[15014]: redir_getreq(2150): The path: json/status
chilli[15014]: redir_getreq(2505): -->> Setting userurl=[http://192.168.182.1:3990/json/status]
chilli[15014]: redir_main(4205): redir_accept: Original request host=192.168.182.1:3990
chilli[14920]: dhcp_receive_ip(3794): Address found
chilli[15014]: redir_wispr2_reply(994):
chilli[14920]: chilli_handle_signal(386): caught 18 via selfpipe
chilli[14920]: _sigchld(316): child 15014 terminated
chilli[14920]: child_remove_pid(138): Freed child process 15014 [[redir]]
chilli[14920]: dhcp_receive_ip(3794): Address found
chilli[14920]: dhcp_receive_ip(3794): Address found
chilli[14920]: dhcp_receive_ip(3794): Address found

[chillilog.txt](https://github.com/coova/coova-chilli/files/638721/chillilog.txt)

**Comment by nzamps** [comment]
Add  --enable-json to your configure

**Comment by xewonder** [comment]
I think it is....?

From compile log:

autoreconf: Leaving directory `.'
(cd /home/denisd/14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/coova-chilli-1.3.2/./; if [ -x ./configure ]; then /usr/bin/find /home/denisd/14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/coova-chilli-1.3.2/ -name config.guess | xargs -r chmod u+w; /usr/bin/find /home/denisd/14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/coova-chilli-1.3.2/ -name config.guess | xargs -r -n1 cp /home/denisd/14.07/openwrt/scripts/config.guess; /usr/bin/find /home/denisd/14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/coova-chilli-1.3.2/ -name config.sub | xargs -r chmod u+w; /usr/bin/find /home/denisd/14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/coova-chilli-1.3.2/ -name config.sub | xargs -r -n1 cp /home/denisd/14.07/openwrt/scripts/config.sub; AR=mipsel-openwrt-linux-uclibc-ar AS="mipsel-openwrt-linux-uclibc-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kec -mdsp -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float" LD=mipsel-openwrt-linux-uclibc-ld NM=mipsel-openwrt-linux-uclibc-nm CC="mipsel-openwrt-linux-uclibc-gcc" GCC="mipsel-openwrt-linux-uclibc-gcc" CXX="mipsel-openwrt-linux-uclibc-g++" RANLIB=mipsel-openwrt-linux-uclibc-ranlib STRIP=mipsel-openwrt-linux-uclibc-strip OBJCOPY=mipsel-openwrt-linux-uclibc-objcopy OBJDUMP=mipsel-openwrt-linux-uclibc-objdump SIZE=mipsel-openwrt-linux-uclibc-size CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kec -mdsp -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float " CXXFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kec -mdsp -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float " CPPFLAGS="-I/home/denisd/14.07/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include -I/home/denisd/14.07/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/include -I/home/denisd/14.07/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/denisd/14.07/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/include " LDFLAGS="-L/home/denisd/14.07/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib -L/home/denisd/14.07/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/lib -L/home/denisd/14.07/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/denisd/14.07/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/lib "   ./configure --target=mipsel-openwrt-linux --host=mipsel-openwrt-linux --build=x86_64-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls    --disable-chilliredir --disable-dnslog --disable-miniportal --disable-useragent --disable-largelimits --disable-uamdomainfile --without-matrixssl --without-cyaxssl --with-openssl --enable-libjson ; fi; )

**Comment by nzamps** [comment]
I don't see it.  Add it after --enable-libjson

**Comment by xewonder** [comment]
I finally fixed it!

in my make file i added

	$(if $(CONFIG_COOVACHILLI_JSON),--enable,--disable)-libjson \
	+ $(if $(CONFIG_COOVACHILLI_JSON),--enable,--disable)-json \

and

DEPENDS:=+kmod-tun +librt ++libjson-c +COOVACHILLI_MATRIXSSL:libmatrixssl +COOVACHILLI_CYASSL:libcyassl +COOVACHILLI_OPENSSL:libopenssl

finally compiled and seems to be working

Thank you all for your help! Great community!
