### ISSUE TITLE
How can I disable debug messages

### ISSUE THREAD

**Issue by streetonice** [coova/coova-chilli#318]
Hi everybody
i'm using  Openwrt Snapshots version  and Coovachilli 1.3.2

How  can I disable debug messages show on syslog (logread)

> Fri Dec  9 12:39:06 2016 user.debug : IPv6 disabled
Fri Dec  9 12:39:06 2016 user.debug : DHCP Listen: 10.11.0.1
Fri Dec  9 12:39:07 2016 user.debug : UAM Listen: 10.11.0.1
Fri Dec  9 12:39:07 2016 user.debug : uamdomain facebook.com
Fri Dec  9 12:39:07 2016 user.debug : PID 16471 saving options to /var/run/chilli.16351.cfg.bi

Thank you

**Comment by gbaligh** [comment]
Hi,

Can you try to set "loglevel" option to 0 ? This will set the syslog level to Error message only.

**Comment by streetonice** [comment]
Thank you for reply ,
I try to run "chilli --loglevel=0" in command line, not working debug messages  still show on syslog (logread)

> 13360 root      4264 S    chilli --loglevel=0

after run

> Tue Dec 13 11:18:31 2016 user.debug : IPv6 disabled
Tue Dec 13 11:18:31 2016 user.debug : DHCP Listen: 10.11.0.1
Tue Dec 13 11:18:31 2016 user.debug : UAM Listen: 10.11.0.1
Tue Dec 13 11:18:31 2016 user.debug : uamdomain google.com
Tue Dec 13 11:18:31 2016 user.debug : PID 13574 saving options to /var/run/chilli.13360.cfg.bin

any idea?

Thank you

**Comment by nzamps** [comment]
Those should be the only lines that show in syslog. Do any appear after that?  The problem is the setlogmask to filter the msgs comes after the options are loaded and those debug lines are printed.

**Comment by gbaligh** [comment]
related to #119

**Comment by streetonice** [comment]
Thank you everybody i got it
