### ISSUE TITLE
Too sharp upload bandwidth limit on 1gbps wired network

### ISSUE THREAD

**Issue by mcitew** [coova/coova-chilli#32]
Someone reported the problem in detail in 2012.

http://www.coova.org/node/5171

Tested upto kernel 3.10.x, the problem still exist. Almost indepedent of coova chilli version, but it has been confirmed to only shows up on giga wired network and newer kernel versions.

Perhaps someone can bisect the kernel version to nail to the changes in the kernel which triggers this.

**Comment by mcitew** [comment]
Just did a test based on version 1.3.1-svn, yeah problem is still there.

**Comment by mcitew** [comment]
Did a lot of testing on different kernel versions. So far my testing results reveal this :-1: 
1. Kernel version < 3.6 are working ( tested both 3.6 and 3.6.11 ).
2. Kernel version  > 3.7 are not working properly with respect to gigabit ethernet ( upload bandwidth only around 100 kbit/s no matter what's the value of WISPr-Bandwidth-Max-Up. Tested both 3.7 and 3.7.10.

Also tested kernel 3.7-rc1, also not working properly. So the difference come from the patch-3.7-rc1.xz.

**Comment by mcitew** [comment]
fixed by 'ethtool -K ethX gro off'

**Comment by knumat** [comment]
Hi @mcitew ,

I appreciate all of the testing information above that you provided above.  I was able to resolve a similar issue by setting "gro off" on the LAN interface.

Did you ever figure out whether this is a bug in the Linux kernel, or a bug in CoovaChilli?  Personally, I am only seeing the issue when CoovaChilli is running.

Thanks for any additional information you can provide!
