### ISSUE TITLE
JS library alternative

### ISSUE THREAD

**Issue by mpangrazzi** [coova/coova-chilli#33]
Hi all,

don't know if it's the right place, but I've done some heavy lifting to ChilliLibrary.js in order to adapt it to the particular setup of my company.

You can find it here: [https://github.com/mpangrazzi/pepper](https://github.com/mpangrazzi/pepper)

It could be useful if someone uses a modern JS build system like [Browserify](http://browserify.org). I've plans to make it also fully usable with [node.js](http://nodejs.org), so one could easily build a smart client using, for example, [nw.js](http://nwjs.io).

Cheers,
Michele

**Comment by Spomky** [comment]
+1

**Comment by wlanmac** [comment]
Happy to add to the distribution... either to replace ChilliLibrary or in a contrib directory..

**Comment by mpangrazzi** [comment]
Thank you! 

I've just added Node.js compatibility and released version 1.1.0.
Right now, I think it's more a stand-alone module, so it should be placed in a "contrib" folder.

As soon as I can, I will provide a full example (with some UI) to do a CHAP login using Pepper.

**Comment by mpangrazzi** [comment]
Hi David,

I've an almost-ready login page (with UI) example which I can easily adapt to Coova style (e.g. adding Coova logo, etc). 

As I writed before, replacing ChilliLibrary would mean also update miniportal, which will require a bit more work. Or, I can do a pull request with a Pepper-powered miniportal placed in a "contrib" directory. 

Which way do you prefer?

Thanks,
Michele

**Comment by pinkra** [comment]
Good, very interesting work.. put it in a contrib for the moment, we will consider to replace native libraries for the future.

**Comment by mpangrazzi** [comment]
Thanks! 
Before doing that, I just want to add PAP login support, since right now it supports only CHAP.
Then I'll open a PR and put the lib in a contrib folder.

**Comment by pinkra** [comment]
Good!

2015-07-03 15:23 GMT+02:00 Michele Pangrazzi <notifications@github.com>:

**Comment by pinkra** [comment]
PAP is quite insecure.. why do you want to implement it?

**Comment by mpangrazzi** [comment]
Three main reasons:

- CoovaChilli already supports it;
- Sometimes you need to forward authentication (on RADIUS side) to other system that may support only PAP;
- PAP is not always insecure. If CoovaChilli is compiled and correctly configured with HTTPS support, you can securely logon with PAP. Instead, with plain HTTP this is not true (as you said) and one can easily do a transparent MITM attack.

It shouldn't be too hard to implement, so stay tuned :)

**Comment by muratbeser** [comment]
@pinkra I'm agreed with @mpangrazzi HTTPS is the way, we can choice method PAP or CHAP it on us actually.

**Comment by pinkra** [comment]
Right!

**Comment by mpangrazzi** [comment]
I've finally added PAP authentication protocol support to [Pepper](https://github.com/mpangrazzi/pepper). Next step will be making a good replacement of miniportal based on it (see related issue).
