### ISSUE TITLE
coova not installed in ubuntu 14.04LTS 64BIT,

### ISSUE THREAD

**Issue by chinmoy4c** [coova/coova-chilli#336]
coova not installed in ubuntu 14.04LTS 64BIT,
please help me out, please give me commands for this,

thank
sorry for bad english

**Comment by irongomme** [comment]
Hi, GIYF : 
https://help.ubuntu.com/community/WifiDocs/CoovaChilli#Install_CoovaChilli

**Comment by sevan** [comment]
There also the [INSTALL file](https://raw.githubusercontent.com/coova/coova-chilli/master/INSTALL) which is bundled with coova.
