### ISSUE TITLE
Coova Chilli doesn't redirect to login page

### ISSUE THREAD

**Issue by MiroslavMerinsky** [coova/coova-chilli#337]
Coova Chilli doesn't redirect to login page. I had tested coova chilli on OpenWRT, then I built application for an embedded Linux similar to OpenWRT. I built it in same way like on OpenWRT and I am using the same configuration, which works on OpenWRT, but not on the embedded Linux.

**OpenWRT:**
dns.c: 210: 0 (Debug) checking .linkyfi.com [rakldxvs]
dns.c: 187: 0 (Debug) It was a dns record type: 6 class: 1
dns.c: 337: 0 (Debug) SOA record
dhcp.c: 5273: 0 (Debug) Layer2 PROT: 0x86dd dropped
dhcp.c: 5273: 0 (Debug) Layer2 PROT: 0x86dd dropped
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: www.google.cz
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: www.google.cz
dns.c: 210: 0 (Debug) checking .linkyfi.com [www.google.cz]
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: clients3.google.com
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: clients3.google.com
dns.c: 210: 0 (Debug) checking .linkyfi.com [clients3.google.com]
dns.c: 187: 0 (Debug) It was a dns record type: 5 class: 1
dns.c: 336: 0 (Debug) CNAME record clients3.google.com.
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
**redir.c: 2117: 0 (Debug) The path: generate_204
redir.c: 2441: 0 (Debug) -->> Setting userurl=[http://172.217.23.206/generate_204]
redir.c: 4063: 0 (Debug) redir_accept: Original request host=172.217.23.206
redir.c: 4172: 0 (Debug) ---->>> resetting challenge: 9efe7d42e9ca85e73df67084291be0bc
redir.c: 992: 0 (Debug) redir_wispr2_reply**
chilli.c: 379: 0 (Debug) caught 18 via selfpipe
chilli.c: 310: 0 (Debug) child 1174 terminated
chilli.c: 310: 0 (Debug) child 1228 terminated
chilli.c: 135: 0 (Debug) Freed child process 1228 [[redir]]
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: www.idnes.cz
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: www.idnes.cz
dns.c: 210: 0 (Debug) checking .linkyfi.com [www.idnes.cz]
dns.c: 187: 0 (Debug) It was a dns record type: 5 class: 1
dns.c: 336: 0 (Debug) CNAME record www.idnes.cz.
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
**redir.c: 2117: 0 (Debug) The path: 
redir.c: 2441: 0 (Debug) -->> Setting userurl=[http://www.idnes.cz/]
redir.c: 4063: 0 (Debug) redir_accept: Original request host=www.idnes.cz
redir.c: 992: 0 (Debug) redir_wispr2_reply**
chilli.c: 379: 0 (Debug) caught 18 via selfpipe
chilli.c: 310: 0 (Debug) child 1229 terminated
chilli.c: 135: 0 (Debug) Freed child process 1229 [[redir]]

**Embedded Linux:**
ns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: mtalk.google.com
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: ntp.nict.jp
dhcp.c: 3509: 0 (Debug) dropping non-IPv4
dhcp.c: 5060: 0 (Debug) Layer2 PROT: 0x86dd dropped
dhcp.c: 5060: 0 (Debug) Layer2 PROT: 0x86dd dropped
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: android.clients.google.com
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: mtalk.google.com
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: www.idnes.cz
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: ntp.nict.jp.--dns1=8.8.8.8
dhcp.c: 5060: 0 (Debug) Layer2 PROT: 0x86dd dropped
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: clients3.google.com
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: android.clients.google.com.--dns1=8.8.8.8
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: mtalk.google.com.--dns1=8.8.8.8
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: www.idnes.cz
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: ntp.nict.jp.--dns1=8.8.8.8
dhcp.c: 5060: 0 (Debug) Layer2 PROT: 0x86dd dropped
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: clients3.google.com
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: android.clients.google.com.--dns1=8.8.8.8
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: mtalk.google.com.--dns1=8.8.8.8
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: www.idnes.cz.--dns1=8.8.8.8
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: www.idnes.cz
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1
dns.c: 194: 0 (Debug) DNS: www.google.cz
dhcp.c: 5622: 0 (Debug) ARP: A0-E4-53-87-4E-AA asking about 192.168.182.1
dhcp.c: 5506: 0 (Debug) ARP: Replying to 192.168.180.1 / A0-E4-53-87-4E-AA
dhcp.c: 5543: 0 (Debug) ARP: Received other ARP than request!
dns.c: 187: 0 (Debug) It was a dns record type: 1 class: 1

Could someone help me with this issue?

Thank you.

Miroslav

**Comment by nzamps** [comment]
Something looks very wrong with the embedded build - look at the DNS lines like: 

dns.c: 194: 0 (Debug) DNS: ntp.nict.jp.--dns1=8.8.8.8

That —dns1 shouldn’t be there! 

What does your configure line look like?

-
brian

**Comment by MiroslavMerinsky** [comment]
Yes, on the first view it seems there is something bad with DNS, but what?

**Here is my chilli.conf:**
radiussecret		"\*\*\*\*\*\*\*\*"
uamsecret		"\*\*\*\*\*\*\*\*"

locationname 		"\<human readible location name\>"
radiuslocationname 	"\<SSID\>,\<sub-ID\>"
radiuslocationid 	"isocc=\<cc\>,cc=\<idd\>,ac=\<ac\>,network=\<SSID\>"

radiusserver1		94.23.89.14
radiusnasid		"206E9CDD3319"
\# Your device's LAN interface on which to put the hotspot
dhcpif 			br0

**dns1			8.8.8.8
dns2			8.8.4.4**
	
\# Tunnel and Subnet 
tundev 			'tun0'
net			192.168.180.0/22	\# For 1000 addresses. Default is 182/24 subnet
uamlisten		192.168.182.1	\# keep it at 182.1 despite the 180/22 subnet
lease			86400		\# 1 day
leaseplus		600		\# plus 10 minutes

\# Universal access method (UAM) parameters
uamserver		"http://linkyfi.com/login"
uamuiport 		80
uamaliasname 		login

uamallowed	"customer.hotspotsystem.com,www.directebanking.com,betalen.rabobank.nl,ideal.ing.nl,ideal.abnamro.nl,www.ing.nl"
uamdomain	".linkyfi.com"

interval 		3600		# config file and host lookup refresh

\# Add the chilli firewall rules
ipup '/etc/chilli/up.sh'
ipdown '/etc/chilli/down.sh'

Thank you.

Miroslav

**Comment by MiroslavMerinsky** [comment]
I am adding build configuration:

`./configure --prefix=$(INSTALL_DIR) --host=mips-linux-uclibc --with-nfcoova --with-ipv6=no --localstatedir=/var --sysconfdir=/etc --runstatedir=/var/run --sbindir=/usr/sbin --bindir=/usr/bin`

**chilli -h**:
...
`ENABLE_CHILLIQUERY ENABLE_COA ENABLE_RADPROXY ENABLE_DHCPRADIUS ENABLE_IEEE8021Q ENABLE_JSON ENABLE_LEAKYBUCKET ENABLE_UAMANYIP ENABLE_UAMUIPORT HAVE_NETFILTER_COOVA`
...

Best Regards,

Miroslav

**Comment by MiroslavMerinsky** [comment]
The reason why redirect doesn't work is there is no DNS response to DNS queries from a clients (mobile phone, PC).

Miroslav

**Comment by MiroslavMerinsky** [comment]
It was caused DNS requests from a client weren't routed to WAN properly, so the client didn't send HTTP request.

**Comment by fjvillegas** [comment]
Hi, 

I am having the same problem. Could you please share how you solve this issue? 

Thank you,


Francisco
