### ISSUE TITLE
make inside src/linux fails

### ISSUE THREAD

**Issue by laoshaw** [coova/coova-chilli#339]
the default ./configure && make does not build src/linux, when I entered into it and the build fails, why is this not built, or why the build fails?

<pre>
cc  -fPIC -O2 -Wall -I/usr/src/linux-headers-4.4.0-59-generic/include -D_INIT=libxt_coova_init -c -o libxt_coova.o libxt_coova.c;
In file included from /usr/src/linux-headers-4.4.0-59-generic/include/linux/list.h:4:0,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/timer.h:4,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/netdevice.h:28,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/netfilter/x_tables.h:5,
                 from libxt_coova.c:9:
/usr/src/linux-headers-4.4.0-59-generic/include/linux/types.h:14:26: error: conflicting types for ‘fd_set’
 typedef __kernel_fd_set  fd_set;
                          ^
In file included from /usr/include/x86_64-linux-gnu/sys/types.h:219:0,
                 from /usr/include/x86_64-linux-gnu/sys/uio.h:23,
                 from /usr/include/x86_64-linux-gnu/sys/socket.h:26,
                 from /usr/include/netinet/in.h:23,
                 from /usr/include/netdb.h:27,
                 from libxt_coova.c:4:
/usr/include/x86_64-linux-gnu/sys/select.h:75:5: note: previous declaration of ‘fd_set’ was here
   } fd_set;
     ^
In file included from /usr/src/linux-headers-4.4.0-59-generic/include/linux/list.h:4:0,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/timer.h:4,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/netdevice.h:28,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/netfilter/x_tables.h:5,
                 from libxt_coova.c:9:
/usr/src/linux-headers-4.4.0-59-generic/include/linux/types.h:15:25: error: conflicting types for ‘dev_t’
 typedef __kernel_dev_t  dev_t;
                         ^
In file included from /usr/include/x86_64-linux-gnu/sys/uio.h:23:0,
                 from /usr/include/x86_64-linux-gnu/sys/socket.h:26,
                 from /usr/include/netinet/in.h:23,
                 from /usr/include/netdb.h:27,
                 from libxt_coova.c:4:
/usr/include/x86_64-linux-gnu/sys/types.h:60:17: note: previous declaration of ‘dev_t’ was here
 typedef __dev_t dev_t;
                 ^
In file included from /usr/src/linux-headers-4.4.0-59-generic/include/linux/list.h:4:0,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/timer.h:4,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/netdevice.h:28,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/netfilter/x_tables.h:5,
                 from libxt_coova.c:9:
/usr/src/linux-headers-4.4.0-59-generic/include/linux/types.h:19:17: error: conflicting types for ‘nlink_t’
 typedef __u32   nlink_t;
                 ^
In file included from /usr/include/x86_64-linux-gnu/sys/uio.h:23:0,
                 from /usr/include/x86_64-linux-gnu/sys/socket.h:26,
                 from /usr/include/netinet/in.h:23,
                 from /usr/include/netdb.h:27,
                 from libxt_coova.c:4:
/usr/include/x86_64-linux-gnu/sys/types.h:75:19: note: previous declaration of ‘nlink_t’ was here
 typedef __nlink_t nlink_t;
                   ^
In file included from /usr/src/linux-headers-4.4.0-59-generic/include/linux/list.h:4:0,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/timer.h:4,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/netdevice.h:28,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/netfilter/x_tables.h:5,
                 from libxt_coova.c:9:
/usr/src/linux-headers-4.4.0-59-generic/include/linux/types.h:25:26: error: conflicting types for ‘timer_t’
 typedef __kernel_timer_t timer_t;
                          ^
In file included from /usr/include/x86_64-linux-gnu/sys/types.h:132:0,
                 from /usr/include/x86_64-linux-gnu/sys/uio.h:23,
                 from /usr/include/x86_64-linux-gnu/sys/socket.h:26,
                 from /usr/include/netinet/in.h:23,
                 from /usr/include/netdb.h:27,
                 from libxt_coova.c:4:
/usr/include/time.h:103:19: note: previous declaration of ‘timer_t’ was here
 typedef __timer_t timer_t;
                   ^
In file included from /usr/src/linux-headers-4.4.0-59-generic/include/linux/list.h:4:0,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/timer.h:4,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/netdevice.h:28,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/netfilter/x_tables.h:5,
                 from libxt_coova.c:9:
/usr/src/linux-headers-4.4.0-59-generic/include/linux/types.h:45:26: error: conflicting types for ‘loff_t’
 typedef __kernel_loff_t  loff_t;
                          ^
In file included from /usr/include/x86_64-linux-gnu/sys/uio.h:23:0,
                 from /usr/include/x86_64-linux-gnu/sys/socket.h:26,
                 from /usr/include/netinet/in.h:23,
                 from /usr/include/netdb.h:27,
                 from libxt_coova.c:4:
/usr/include/x86_64-linux-gnu/sys/types.h:44:18: note: previous declaration of ‘loff_t’ was here
 typedef __loff_t loff_t;
                  ^
In file included from /usr/src/linux-headers-4.4.0-59-generic/include/linux/list.h:4:0,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/timer.h:4,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/netdevice.h:28,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/netfilter/x_tables.h:5,
                 from libxt_coova.c:9:
/usr/src/linux-headers-4.4.0-59-generic/include/linux/types.h:111:17: error: conflicting types for ‘uint64_t’
 typedef  __u64  uint64_t;
                 ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/stdint.h:9:0,
                 from /usr/include/netinet/in.h:22,
                 from /usr/include/netdb.h:27,
                 from libxt_coova.c:4:
/usr/include/stdint.h:55:27: note: previous declaration of ‘uint64_t’ was here
 typedef unsigned long int uint64_t;
                           ^
In file included from /usr/src/linux-headers-4.4.0-59-generic/include/linux/list.h:4:0,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/timer.h:4,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/netdevice.h:28,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/netfilter/x_tables.h:5,
                 from libxt_coova.c:9:
/usr/src/linux-headers-4.4.0-59-generic/include/linux/types.h:112:17: error: conflicting types for ‘u_int64_t’
 typedef  __u64  u_int64_t;
                 ^
In file included from /usr/include/x86_64-linux-gnu/sys/uio.h:23:0,
                 from /usr/include/x86_64-linux-gnu/sys/socket.h:26,
                 from /usr/include/netinet/in.h:23,
                 from /usr/include/netdb.h:27,
                 from libxt_coova.c:4:
/usr/include/x86_64-linux-gnu/sys/types.h:203:1: note: previous declaration of ‘u_int64_t’ was here
 __u_intN_t (64, __DI__);
 ^
In file included from /usr/src/linux-headers-4.4.0-59-generic/include/linux/list.h:4:0,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/timer.h:4,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/netdevice.h:28,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/netfilter/x_tables.h:5,
                 from libxt_coova.c:9:
/usr/src/linux-headers-4.4.0-59-generic/include/linux/types.h:113:17: error: conflicting types for ‘int64_t’
 typedef  __s64  int64_t;
                 ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/stdint.h:9:0,
                 from /usr/include/netinet/in.h:22,
                 from /usr/include/netdb.h:27,
                 from libxt_coova.c:4:
/usr/include/stdint.h:40:19: note: previous declaration of ‘int64_t’ was here
 typedef long int  int64_t;
                   ^
In file included from /usr/src/linux-headers-4.4.0-59-generic/include/linux/list.h:4:0,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/timer.h:4,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/netdevice.h:28,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/netfilter/x_tables.h:5,
                 from libxt_coova.c:9:
/usr/src/linux-headers-4.4.0-59-generic/include/linux/types.h:134:23: error: conflicting types for ‘blkcnt_t’
 typedef unsigned long blkcnt_t;
                       ^
In file included from /usr/include/x86_64-linux-gnu/sys/uio.h:23:0,
                 from /usr/include/x86_64-linux-gnu/sys/socket.h:26,
                 from /usr/include/netinet/in.h:23,
                 from /usr/include/netdb.h:27,
                 from libxt_coova.c:4:
/usr/include/x86_64-linux-gnu/sys/types.h:235:20: note: previous declaration of ‘blkcnt_t’ was here
 typedef __blkcnt_t blkcnt_t;  /* Type to count number of disk blocks.  */
                    ^
In file included from /usr/src/linux-headers-4.4.0-59-generic/include/linux/kernel.h:6:0,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/list.h:8,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/timer.h:4,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/netdevice.h:28,
                 from /usr/src/linux-headers-4.4.0-59-generic/include/linux/netfilter/x_tables.h:5,
                 from libxt_coova.c:9:
/usr/src/linux-headers-4.4.0-59-generic/include/linux/linkage.h:7:25: fatal error: asm/linkage.h: No such file or directory
compilation terminated.
Makefile:24: recipe for target 'libxt_coova.o' failed
make: *** [libxt_coova.o] Error 1
</pre>

**Comment by laoshaw** [comment]
user mistake, not a bug

**Comment by colinvv2** [comment]
What was the mistake? I am getting the same error when I try to 'make' after setting '--with-nfcoova' configure option.
