### ISSUE TITLE
Error opening configuration files on Raspberry Pi

### ISSUE THREAD

**Issue by luandro** [coova/coova-chilli#350]
I've followed the instructions on the installation page. But I get this error when trying to run `chilli`:

```
chilli[3308]: (Re)processing options [/var/run/chilli.3308.cfg.bin]
chilli[3309]: running chilli_opt on /var/run/chilli.3308.cfg.bin
coova-chilli: Error opening configuration file '/etc/chilli/main.conf'
coova-chilli: Error opening configuration file '/etc/chilli/hs.conf'
coova-chilli: Error opening configuration file '/etc/chilli/local.conf'
chilli[3308]: could not generate configuration (/var/run/chilli.3308.cfg.bin), sleeping one second
```

This seems related to #263 and #116, but neither seem to have been solved. Any ideas?

**Comment by sevan** [comment]
what files do you have in `/etc/chilli`?

**Comment by SheldonBM** [comment]
Hi there, 

Has anyone find the reason or what i can do to resolve this issue?

**Comment by pinkra** [comment]
Check your configurations.

**Comment by gbordier** [comment]
found it, the /etc/init.d/chilli uses 
daemon $exec -c $CONFIG 
but the daemon bin in jessie has a -c option of its own, we need to change this line to 
daemon -- $exec -c $CONFIG 
to prevent arg processing by daemon
