### ISSUE TITLE
Incorrect usage of setsockopt TCP_NODELAY

### ISSUE THREAD

**Issue by Piscolero** [coova/coova-chilli#357]
The function net_open_eth() in src/net.c calls setsockopt with level SOL_SOCKET and option TCP_NODELAY. If you want to set TCP_NODELAY, the level has to be IPPROTO_TCP. The call now actually sets SO_DEBUG.

**Comment by pinkra** [comment]
Can you make a pull request, please?

**Comment by matahr** [comment]
Kernel 4.10.0-22-generic #24-Ubuntu SMP x86_64 GNU/Linux

chilli[21080]: 92 setsockopt(s=2, level=6, optname=1, optlen=4) failed
chilli[21080]: Failed to create dhcp listener on eth0

**Comment by Piscolero** [comment]
Well, it's probably returning ENOPROTOOPT in this case, because it's not a tcp socket.
So I think the setting should be avoided at all since it never worked before.
