### ISSUE TITLE
Coova chilli caps bandwidth also to local domains

### ISSUE THREAD

**Issue by tritone11** [coova/coova-chilli#359]
I set up coova chilli to allow users to use the bandwidth, but when the login also the local captive portal is loading slowly, even if it doesn't make any external call or request. Whenever the user disconnect from chilli, the speed of the captive portal turns back to normal speed.

My guess is that also the captive portal has a capped connection when the user is logged in.

**Comment by stjerno** [comment]
Compile Coova with ' --enable-authedallowed'
use the option: --authedallowed portal_ip to allow unlimited access to portal_ip
or
use the option: --uamauthedallowed
this will allow unlimited acccess to all sites in your uamallowed list.

:)

**Comment by tritone11** [comment]
Hi stjerno, thanks for the useful response,
I think this would solve my problem, but I am running coova chilli on Grase Hotspot, that (as far as I can see) it has a version of Coova Chilli not new enough to have that compile option and the correlated runtime options.

I am opening an issue on Grase Hotspot to see if there's something I can do, because it's Grase itself that compile chilli.

Thanks!!
