### ISSUE TITLE
Closing by "Lost-Carrier"

### ISSUE THREAD

**Issue by ivanfdez** [coova/coova-chilli#361]
I have users in freenas with a session-timeout 84400 (24h) but if the user is offline 10 minutes the session is closed and has to re-enter it, the log appears that the session has been closed for "lost-carrier".

I do not see how to prevent the session from closing

**Comment by nzamps** [comment]
You could set defidletimeout=0

**Comment by nzamps** [comment]
Maybe check your DHCP lease time...

**Comment by ivanfdez** [comment]
I have increased the lease to 7 days, and now it works correctly.
Thank you

**Comment by dkarky0** [comment]
In my case its still same, lost carrier after 7 or 8 hours.
Can anyone help ?
