### ISSUE TITLE
UAMUISSL, browser show "mixed content"

### ISSUE THREAD

**Issue by antoniovalenzuela** [coova/coova-chilli#365]
I enabled HS_UAMUISSL works correctly, but the URL /www/login.chi? It also loads non-secure HTTP content (1.jpg). This causes Chrome to notice Mixed Content (2.jpg).

To temporarily resolve this problem, I omitted the variable HS_UAMHOMEPAGE from the /etc/chilli/functions file (3.jpg), now HS_UAMFORMAT loads with https://   without security warnings (4.jpg).

Please help to solve mixed content problem.

Note: HS_UAMHOMEPAGE does not work in SSL mode

Thanks!!
![1](https://user-images.githubusercontent.com/28113584/27109110-d5be6266-506e-11e7-9310-1ed1f193a351.jpg)
![2](https://user-images.githubusercontent.com/28113584/27109111-d5bf1a3a-506e-11e7-8385-01a3515fce00.jpg)
![3](https://user-images.githubusercontent.com/28113584/27109112-d5ca8c6c-506e-11e7-8a18-c9fa6dcd725a.jpg)
![4](https://user-images.githubusercontent.com/28113584/27109113-d5ccd896-506e-11e7-932e-8048b1128ed8.jpg)

**Comment by antoniovalenzuela** [comment]
Own solution:

Set new var HS_HTTPS
HS_HTTPS = hspot.cl

Replace $HS_UAMLISTEN
HS_UAMFORMAT=https://\**$HS_HTTPS**:\$HS_UAMUIPORT/www/login.chi

Replace $HS_UAMLISTEN and $HS_UAMPORT
HS_UAMHOMEPAGE=https://\**$HS_HTTPS**:\**$HS_UAMUIPORT**/www/coova.html

Note: In my hotspot system add the "email" field to send automatic notifications to the clients with a single user and the password changes every hour.

Home and Login sites both SSL OK!!
![1](https://user-images.githubusercontent.com/28113584/27256256-8fd95a64-537d-11e7-8789-abd73a49ec67.jpg)

Please close the ticket.

**Comment by cheseremtitus24** [comment]
You must enable HS_UAUISSL=on
HS_SSLKEYFILE=/path/to/private_key.key
HS_SSLCERTFILE=/path/to/certificate.crt

**Comment by oumkuda** [comment]
share full chilli config file, please! 
need working ssl

**Comment by cheseremtitus24** [comment]
HS_LANIF=eth1		   # Subscriber Interface for client devices
# WAN interface is optional as it will automatically be picked(if it has an internet connection)
HS_NETWORK=10.1.0.0	   # HotSpot Network (must include HS_UAMLISTEN)
HS_NETMASK=255.255.255.0   # HotSpot Network Netmask
HS_UAMLISTEN=10.1.0.1	   # HotSpot IP Address (on subscriber network)
HS_UAMPORT=3990            # HotSpot UAM Port (on subscriber network)
HS_UAMUIPORT=4990          # HotSpot UAM "UI" Port (on subscriber network, for embedded portal)
HS_UAMUISSL=on  # Enable SSL on port 4990
HS_SSLKEYFILE=/path/to/private_key.key
HS_SSLCERTFILE=/path/to/certificate.crt
#optionally also enable
HS_REDIRSSL=on # Enable portal redirection when user is navigating to a https site when connection is "dnat"-chilli_query [will always cause browser warnings]
HS_DNS1=$HS_UAMLISTEN
HS_UAMFORMAT=https://\$HS_UAMLISTEN:\$HS_UAMUIPORT/www/login.chi
HS_TCP_PORTS="80 443 22 23"
HS_UDP_PORTS="1701 1812 1813 3799"
HS_USE_MAP=on

**Comment by cheseremtitus24** [comment]
secure https traffic is only supported on port 4990. 
3990 is like port 80(http)
4990 is equiv to 443(https)
