### ISSUE TITLE
Disconnect Simultaneous Devices

### ISSUE THREAD

**Issue by mancharagopan** [coova/coova-chilli#366]
I have configured Coovachilli, Freeradius, DaloRadius. All working fine but,
I have a problem with the simultaneous device.

If a user use one device, that user will be disconnected after he exceed the time or the bandwidth and cannot re-login.
But if a user use multiple device with one username, each device getting same amount of bandwidth separately and devices are disconnected one by one when they finish their allocated bandwidth.

I need to disconnect all the sessions of a user when he exceed his bandwidth or time. How can i do it?

**Comment by pinkra** [comment]
You can add some logic (with queries) in your freeradius configuration to return a different bandwidth per device.

**Comment by mancharagopan** [comment]
I don't need different bandwidth per device.
My situation is like this, 
User A has 1 GB limit for 1 month. He is login his credentials on a laptop to access the internet and also he login on his mobile at the same time. So there are two sessions. therefor he is getting 1GB on his mobile and 1GB on his laptop, totally 2GB. Mobile will get disconnected after he finish that 1GB and the laptop will get disconnected after he finished his other 1GB. 

I need user A to get only 1GB limit per month no matter how many devices he use to login at the same time. after 1GB exceeded or time exceeded all the sessions should disconnected.

**Comment by pinkra** [comment]
It's not possible because it means to add something that limit the available traffic per device dynamically while it's limited statically with freeradius replies on session start.

**Comment by mancharagopan** [comment]
Is there any way to modify the disconnect request in freeradius or coovachilli to remove Acct Session ID attribute?

**Comment by nzamps** [comment]
You can delete attributes in freeradius with a config entry kinda like:

````
preacct {
    update request {
         Acct-Session-Id -= "%{request:Acct-Session-Id}"
   }
...

````

**Comment by mancharagopan** [comment]
I cannot find such entry in my freeradius config files. I can only find this entry in /etc/freeradius/default
#         update request {
#               FreeRADIUS-Acct-Session-Start-Time = "%{expr: %l - %{%{Acct-Session-Time}:-0} - %{%{Acct-Delay-Time}:-0}}"
#       }

Can you specify when exactly i can find it?

**Comment by nzamps** [comment]
You'd have to add it

**Comment by mancharagopan** [comment]
Do you want me to add the lines or delete it?

**Comment by mancharagopan** [comment]
I'd like to send the disconnect request without Acct-Session-ID. Is there a way?

**Comment by nzamps** [comment]
You'd have to change the chilli code

**Comment by mancharagopan** [comment]
Can you please explain me how can i change the code?

**Comment by pinkra** [comment]
Why do you want to do that?

**Comment by mancharagopan** [comment]
As I've explained in my first post, i need to disconnect all the sessions of a user when he/she exceed the limit. So i need to disconnect the user instead of a session.

**Comment by nzamps** [comment]
You're probably better off writing a script for freeradius to do what you want.  The rlm_perl module works well (https://wiki.freeradius.org/modules/Rlm_perl)

**Comment by mancharagopan** [comment]
That link is not working for me. Are you mentioning freeradius/module/perl file?

**Comment by wlanmac** [comment]
You have a number of options... all of which are programmed (in one way or another, perhaps using FreeRADIUS support for perl or other languages). 
You can:
- Have your RADIUS server issue ChangeOfAuthorization (CoA) requests to chilli
- Use https://github.com/coova/coova-chilli/blob/master/src/cmdline.ggo#L223 and "update" session parameters using the AccountingResponse
- Or you can do something 'out-of-band' and call chilli_query on the NAS machine to locally terminate sessions

**Comment by reigelgallarde** [comment]
Hello @wlanmac,
Can you explain more on this `Have your RADIUS server issue ChangeOfAuthorization (CoA) requests to chilli'
or can you give me links I can read on....

I using this https://github.com/retailnext/node-radius as my radius server.
So far so good on Authentication and Accounting.

But I'm having a problem on how to issue a disconnect request on chilli.

**Comment by pinkra** [comment]
Hi @reigelgallarde you have to issue a disconnect request through radius. Read here: https://wiki.freeradius.org/protocol/Disconnect-Messages

Here is an example using the radclient tool:
```echo "User-Name=chillispot" | radclient localhost:3779 disconnect radiussecret```
