### ISSUE TITLE
UAM login successful but chilli does not authorize

### ISSUE THREAD

**Issue by bnviki** [coova/coova-chilli#375]
I am using coovachilli on openwrt, with pepper for authentication in UAM captive portal page. When the login is initiated after entering username and password, i get clientstate=1 in pepper and logread shows `chilli.c: 6018: Successful UAM login from username=vikram IP=10.1.0.2`

but there is no internet access, browser gets redirected to login page again. 

chilli_query list : gives this 
`10.1.0.2 dnat 5950752800000003 0 vikram 0/0 0/0 6738/0 2350/0 0 0 0/0 0/0 http://connectivitycheck.gstatic.com/generate_204` 

chilli has not authorized the client. But when i authorize explicitly using chilli_query, everything works fine and chilli_query list shows "pass" for the client 
`10.1.0.2 pass 5950752800000003 1 vikram 17/0 2/0 26517/0 9557/0 0 0 0%/0 0%/0`

What is wrong here?? how do i resolve this?

**Comment by vipinedassery** [comment]
Please make sure you have executed the below line. 

iptables -I POSTROUTING -t nat -o br-lan -j MASQUERADE
