### ISSUE TITLE
iPhone 7 never redirected

### ISSUE THREAD

**Issue by skoubri** [coova/coova-chilli#378]
Clean ubuntu 16.04.2 setup. Compile from 1.4 version with coovachilli only, miniportal enabled , i am getting dhcp, dns but iphone never gets the redirection.

If i manually open 10.1.0.1:3990 on safari i am getting the coova logo and login page after that..

any help please?

**Comment by gbaligh** [comment]
Hi,

This is a known incompatibility problem between coova and some iOS7 devices. It is not specific of Chilli it happens also with other captive portals like mikrotik and unifi.

If you're interested there is a temporary workaround: enabling akamai.net and akamaiedge.net prevents the ios captive portal assistant from popping up, so users can login using Safari (which works).

**Comment by skoubri** [comment]
Thanks for your answer. Actually i am testing on iOS 10.3.2 but managed to bypass the problem in another way. Noticed that if i use the coova.org logo redirection page then the redirection works!.. So i am fine for the moment. Thanks
