### ISSUE TITLE
Issue with coovachilli in case of wifi roaming

### ISSUE THREAD

**Issue by chirayu-patel** [coova/coova-chilli#391]
When the user connect to one AP and then moves on to the next AP, the splash page comes back up.. How to reauthenticate the user instead of showing him the splash page .. Please help..

**Comment by wlanmac** [comment]
One typical way is to use "MAC Authentication" (implemented in your RADIUS server to authorized sessions that are "roaming"). Or you can organize your multiple APs into a bridged network with a single chilli serving them all (in which case chilli will not even notice the "roaming", if you don't want it to). You will have to decide if you want to 'know' about the roaming event or not.

**Comment by chirayu-patel** [comment]
I agree to both your solutions but following are the problems :

1. We need captive portal based. So direct Mac auth is a problem
2. For the second solution, will need to have a central breakout of internet.. Local breakout of internet from each AP won't work

**Comment by wlanmac** [comment]
The thing is, you will never be able to do it "captive portal based" because the client device interacts with the portal "too late" to keep the session going... your portal could use cookie and more or less "seamlessly" login the user automatically, but that may not work well with various OS captive portal detections.

**Comment by gufmar** [comment]
We've implemented such a "Workaround" solution.
First your login page should try to set a cookie.
If the client (mostly captive portal popups) does not accept, store and provide cookies you can get the MAC address provided from coovachilli in the url and store them on server side.
On all further login attempts the server before generating the standard login page can check if the MAC is already known. If yes generate a prefilled or "one-click" or "autologin" version of the captive portal login mask. 
But be aware that MAC can be forged. So it's everything else than a secure solution.
