### ISSUE TITLE
The Portal Captive Page can not appear automatically

### ISSUE THREAD

**Issue by SanMu9** [coova/coova-chilli#392]
I have finished the CoovaChilli configuration ，but when I use another PC to test ，The Portal Captive Page can not appear automatically，but I can enter the page by searching http://10.1.0.1:4990 in my browser.what are the possible causes?The login page can only appear in wireless environment（I use two PC and one switch to test）？

Best Regards

**Comment by gbaligh** [comment]
Hi, 

Do you have the PC connect to a WiFi switch ?
You Coova is configured to use both interface WiFi and ETH ?
Can you share you conf, setup and logs ?

**Comment by SanMu9** [comment]
@gbaligh 
(Sorry,I'm just a student and a rookie in this area,so I may not understand what you said competly)
My switch is NETGEAR SWITCH
I use interface ETH(eth0) and USB(eth1)(not wireless)
My PC1 's USB NIC and PC2 connected to Switch
my /etc/chilli/defaults :
HS_WANIF=eth0            # WAN Interface toward the Internet
HS_LANIF=eth1              # Subscriber Interface for client devices
HS_NETWORK=10.1.0.0        # HotSpot Network (must include HS_UAMLISTEN)
HS_NETMASK=255.255.255.0   # HotSpot Network Netmask
HS_UAMLISTEN=10.1.0.1      # HotSpot IP Address (on subscriber network)
HS_UAMPORT=3990            # HotSpot UAM Port (on subscriber network)
HS_UAMUIPORT=4990          # HotSpot UAM "UI" Port (on subscriber network, for embedded portal)

# HS_DYNIP=
# HS_DYNIP_MASK=255.255.255.0
# HS_STATIP=
# HS_STATIP_MASK=255.255.255.0
# HS_DNS_DOMAIN=

# OpenDNS Servers
HS_DNS1=10.1.0.1
...

My ifconfig :
eth0      Link encap:Ethernet  HWaddr 00:0c:29:25:dc:3b  
          inet addr:192.168.68.130  Bcast:192.168.68.255  Mask:255.255.255.0
          inet6 addr: fe80::20c:29ff:fe25:dc3b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3116 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2234 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1521480 (1.5 MB)  TX bytes:308937 (308.9 KB)

eth1      Link encap:Ethernet  HWaddr 00:0e:c6:d3:50:a6  
          inet6 addr: fe80::20e:c6ff:fed3:50a6/64 Scope:Link
          UP BROADCAST RUNNING PROMISC  MTU:1500  Metric:1
          RX packets:2717 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1830 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:235956 (235.9 KB)  TX bytes:228361 (228.3 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:4 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:449 (449.0 B)  TX bytes:449 (449.0 B)

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:10.1.0.1  P-t-P:10.1.0.1  Mask:255.255.255.0
          UP POINTOPOINT RUNNING  MTU:1500  Metric:1
          RX packets:1473 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1431 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:100 
          RX bytes:103711 (103.7 KB)  TX bytes:179859 (179.8 KB)
