### ISSUE TITLE
Redirect On JSON Interface

### ISSUE THREAD

**Issue by EngEryx** [coova/coova-chilli#400]
Hi guys,

I have configured coova-chilli and built  a deb file for ubuntu, installed and it is running ok.

I then tried to access the json interface but all I am getting a redirect to the login page.

I had configured to include proper json libraries before building the deb file.

What could be the issue ?

LINK: I'm testing this link: http://10.1.0.1:3990/json/status

I was expecting some JSON Response but I get redirected to login page.

**Comment by florianwagner81** [comment]
Hey @EngEryx,
this might be a duplicate to [this ](https://github.com/coova/coova-chilli/issues/95) issue, atm I am having the exact same issue that your report on my system as well. 
If you find another fix, let me know.
Cheers man

**Comment by forgaoqiang** [comment]
I think i have the same problem, with new edition chilli 1.3 or above, JSON interface just redirect user to login page without any JSON return

**Comment by vsidou** [comment]
you need to add to ./configure the following parameters : 
--enable-libjson
--enable-json
Otherwise the json interface will not work and will give a redirect.
If you build the debian package, just add those parameters to chilli_src/debian/rules file.

**Comment by EngEryx** [comment]
Hi Guys, It worked fine. Thanks all.

I build the deb package on ubuntu 16.04.

Run the configuration command and used debuild.

After I tested the interface works fine. But I had to patch some scripts to support PAP login using some Perl Script.

If you are having an issue on the same let me know. I can even send you the .deb I used on my system.

Cheers guys
