### ISSUE TITLE
CoovaChilli ARP problem when using DHCP Relay

### ISSUE THREAD

**Issue by ObaidAshraf** [coova/coova-chilli#412]
Hello all..
I am trying to configure CoovaChilli 1.4 with DHCP relay option in order to use external/backend DHCP server. Client is getting correct IP address from the backend DHCP server but no redirection is occurring. After searching on Google i came to know that it is because chilli is unable to forward DNS responses to the client due to which redirection is not happening. In the ARP table, i see client has MAC address as "00:00:00:00:00:00" which means router is unable to resolve MAC for the client.
I am unable to figure out this problem, i tried iptables, ebtables as well but no luck.
Below is the configuration of coovachilli.

# ## main.conf
# THIS FILE IS AUTOMATICALLY GENERATED
cmdsocket       /var/run/chilli.ath0.sock
unixipc         chilli.ath0.ipc
pidfile         /var/run/chilli.ath0.pid
# #net		10.0.1.0/255.255.255.0
uamlisten	10.0.1.1
# #dhcplisten	192.168.4.1
uamport         3990
dhcpif		ath0
uamallowed	"10.0.1.1,192.168.1.12,192.168.1.254,www.intcomcorp.com,"
dynip		192.168.1.0/24
uamanydns
uamanyip

#layer3
dhcpstart 2
dhcpend 151
domain "lan"
dns1 "8.8.8.8"
dns2 "8.8.4.4"
uamhomepage http://192.168.1.12/
wwwdir /etc/chilli/www
wwwbin /etc/chilli/wwwsh
uamuiport 4990
localusers /etc/chilli/ath0/localusers
locationname "My HotSpot"
radiuslocationname "My_HotSpot"
radiuslocationid "isocc=,cc=,ac=,network=Coova,"

# ## hs.conf
radiusserver1	"127.0.0.1"
radiusserver2	"127.0.0.1"
radiussecret	"testing123"
radiusauthport  1812
radiusacctport  1813
uamserver	"http://192.168.1.12/hotspotlogin.php"
radiusnasid	"nas123"

papalwaysok
uamaliasname "chilli"
adminupdatefile "/etc/chilli/ath0/local.conf"
uamsecret "uamsecret"

# ## local.conf
dhcpgateway=192.168.1.254
dhcpgatewayport=67
dhcprelayagent=192.168.1.11

Here are the logs of the coovachilli with the above configurations:
https://pastebin.com/EASQwVTg

Below are some of the important snapshots:

Routes table:
![routes](https://user-images.githubusercontent.com/10379110/34042773-0d9a1832-e1c0-11e7-985e-4ffa2412e635.PNG)

Neighbors:
![ip_neigh](https://user-images.githubusercontent.com/10379110/34042781-10fa9286-e1c0-11e7-8edd-733fd837eea0.PNG)

ifconfig output:
![ifconfig](https://user-images.githubusercontent.com/10379110/34042804-29536ace-e1c0-11e7-949d-bd1778cb25f4.PNG)

arp table of the AP:
![arp_table](https://user-images.githubusercontent.com/10379110/34042811-2f405b40-e1c0-11e7-8c3b-35d8917d7dac.PNG)

Kindly help me to resolve this issue and let me know if i am making a mistake somewhere.

**Comment by tranvanhoa533** [comment]
Hi @ObaidAshraf, I have a same problem. Have you solved it?
