### ISSUE TITLE
chilli session timeout

### ISSUE THREAD

**Issue by ankers1984** [coova/coova-chilli#419]
so i have an issue that when a user logs out, the session timeout stops and then restarts when user logs back in...how would i get the session to end once a user log's out and then restart with the right throttling options when they log back in?!

Thanks in  advance

**Comment by pinkra** [comment]
Please, clarify what you mean with login / logout.

**Comment by ankers1984** [comment]
thanks for the reply, 
so when a user hits the splash page...they capture login details as well as T&C'etc. We have it set so that when they drop back onto the network, they then get connected automatically. this means that when they leave the network, the timeout should reset so that throttling will also reset. 

what i am finding is that regardless of when a user leaves the network, the timeout is just stopping and then restarting when they go back on, rather than resetting. If that makes sense?!

**Comment by ankers1984** [comment]
anybody?!
