### ISSUE TITLE
Have only one website for the project

### ISSUE THREAD

**Issue by Spomky** [coova/coova-chilli#42]
Hi,

Thank you for this great project.
I follow your work for about 2 years and I saw lot of changes.
The reason why I open this issue is that, as far as I know, there are at least three websites to get informations, binaries, source code, issue report or just contact maintainers:

* http://www.coova.org
* this [organization on Github](https://github.com/coova)
* [LinkedIn](https://www.linkedin.com/groups/Coova-Network-Access-Provisioning-Control-158903).

It could be a little bit confusing for people interested in contributing to this project.
Is it planned to centralized this project into a single website?
Is this organization the main point for all contributions?

**Comment by wlanmac** [comment]
Sorry for the confusion.. The plan is to slim down and reorganize the website as a github site and use github to organize development / patches. Issues will increasingly go through github, and there is a bit of a LinkedIn support group.

**Comment by Spomky** [comment]
Great. Thanks.
