### ISSUE TITLE
DaloRadius + Coovachilli / Trouble with WiSPr

### ISSUE THREAD

**Issue by padagoal** [coova/coova-chilli#425]
Using Daloradius, i can create Profiles for Users.

In the Profile, i create with Vendors, in the list i have 2 options, for Coovachilli:

*ChilliSpot
*WiSPr

I try the option of ChilliSpot, like Max-Octets, Up and Down and everything works fine.
But, when i use, WiSpr, nothing works, like the redirection, logoff, Session-Terminate-Time.

I use for Session-Terminate-Time 2018-02-09T17:45:00-03:00, the right sintax

**Comment by pinkra** [comment]
Why do you want to use WiSPr ?
