### ISSUE TITLE
Access to other services on chilli router

### ISSUE THREAD

**Issue by jarek556** [coova/coova-chilli#428]
Hello!
I have some services (www,ssh,ftp) on chilli router. If chilli is working, I'm not able to access them from LAN - even from authenticated clients. Is there any option to change it ?

**Comment by nzamps** [comment]
If your default policy on your iptables INPUT chain is DROP then you'll need to add ACCEPT rules into the INPUT chain e.g.

iptables -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT

**Comment by pinkra** [comment]
With LAN do you mean from the hotspot network? What ip do you use for addressing the router from the LAN ?

**Comment by JarekGit55** [comment]
Problem:
Default iptable rules created by chilli, deny access to all services on chilli router except chilli services. So if you have your own apache or ssh on chilli, you will not be able to access it.
Solution:
To allow access to other services on chilli router you have to put your rules to up.sh or ipup.sh in /etc/chilli/
