### ISSUE TITLE
coovachilli not working any more

### ISSUE THREAD

**Issue by mfaroukg** [coova/coova-chilli#442]
I am using coovachilli almost now for 4 years, suddenly my customers can't access the login page any more and the users who are authorized by MAC address are not able to brows the server. 

I have done lots of debugging and the reason is not clear.

I have tried 1.3.0 and 1.4.0 on both ubuntu 14 and ubuntu 16 and same results were found.

I created isc-dhcp-server along with customized iptables filters and apache2 redirect but they are working fine as I used simple configurations.

I think there was an unattended upgrade on ubuntu messed up the function of the coovachilli, 
any one facing the same issue ? and how to solve it?

**Comment by mfaroukg** [comment]
I found the issue, it was in the kernel version 4.4.0-130, when i revert back to 4.4.0-127 it works again.
dpkg -l | grep linux
apt install linux-image-extra-4.4.0-127-generic linux-image-4.4.0-127-generic linux-headers-4.4.0-127 linux-headers-4.4.0-127-generic 
apt remove linux-image-extra-4.4.0-130-generic linux-image-4.4.0-130-generic linux-headers-4.4.0-130 linux-headers-4.4.0-130-generic 

please check what is the issue in the new linux kernel!!!

**Comment by sjbeskur** [comment]
@mfaroukg good find.  We too have experienced this same issue and have duplicated this in our lab.  Your fix work but it would be good to know what has caused this.   Did you build coova with this Kernel or upgrade the Kernel after coova was built?

**Comment by meyerj** [comment]
I had the same issue running Coova 1.4 on Ubuntu Trusty Witz the latest -lts-xenial kernel (4.4.0-130). Downgrading to 127 as suggested by @mfaroukg solved the problem.

I did some debugging with tcpdump and it seems like ARP replies sent by Coova are not received by the clients, although visible when sniffing the subscriber interface on the same machine that is running Coova. DHCP works, but clients cannot reach the gateway after they got an IP.

**Comment by imtase** [comment]
same issue, solved by recompile and reinstall coova

**Comment by mfaroukg** [comment]
@sjbeskur found in all cases related to affected kernel

**Comment by heruan** [comment]
I'm experiencing the same on Ubuntu 18.04 Server (kernel 4.15.0-3). I think this should be reopened, since it is not fixed (and downgrading is a workaround, not a solution).

@mfaroukg Are you able to run CoovaChilli on the latest kernels?
