### ISSUE TITLE
Can't compile Openwrt 18.06.2 with coovachilli

### ISSUE THREAD

**Issue by Helias** [coova/coova-chilli#480]
OS: **Ubuntu 18.04.2 LTS**

I'm trying to compiling openwrt firmware with the following target system
target system: **MediaTek Railink MIPS**
subtarget: **MT7620**
target profile: **ASUS RT-AC51U**

before **make menuconfig** I update and install the packages and configuration available with:

> $ ./scripts/feeds update -a
> $ ./scripts/feeds install -a

Afterwards I do:

> $ make menuconfig
> - Images configuration / separated feeds
> - Base System -> libpthread, librt, libstdcpp
> - Kernel -> Kernel Modules -> kmod-tun
> - Utilities -> Editors -> nano
> - Utilities -> haserl
> - Network -> File Transfer -> curl + wget
> - Network -> Captive Portal -> coovachilli

and then:

> $ make -j 8

Now I get a generic error about "world", so I type:

> $ make package/coova-chilli/{clean,compile} -j1 V=s

the results is here: https://pastebin.com/MgTF5RFr

How can I resolve?

**Comment by reinerotto** [comment]
I am compiling coova-chilli for similar HW without problems, from TRUNK. Strange, that you try to use coova 3.0 . Should be 4.x . So, just download fresh build env, and _only_ select coova-chilli as additional package. Does this work ? (There is no need to explicitly include kmod-tun etc.)

**Comment by Helias** [comment]
For openwrt branch master with coovachilli 1.4.0, it works, with openwrt-18.0.2 with coovachilli 1.3.x it doesn't work.

I need coovachilli 1.3.x, I don't know if I need to install any **system** requirements to compile correctly coovachilli, I think that the problem is my system requirements or some missing libraries unselected on menuconfig.

Any suggestion for missing system requirements?

**Comment by reinerotto** [comment]
>or some missing libraries unselected on menuconfig.< 
Then do fresh build, with dfeault .config, only coova-chilli selected as additional package. In case, that works, then do a "diff" on working and non-working build systems .config

**Comment by Helias** [comment]
Done, I got the same error

**Comment by reinerotto** [comment]
Interesting, that openwrt 18.06.2 still uses coova 3.0 ; anyway, I will build an image for my "workhorse" device (ZBT-WE826) over night, incl. coova. And then I'll see. I also have ubuntu 18.02.LTS

**Comment by reinerotto** [comment]
Why is using coova 3.x a _MUST_ ?

**Comment by reinerotto** [comment]
I compiled openwrt 18.06.2 over night on ubuntu 16.04 , incl. coova-chilli 3.0: no problem.
Now compiling on ubuntu 18.04 . 
Did you use any special options to configure the coova-chilli package, _or_ just using the default ?

**Comment by Helias** [comment]
I enabled only this coovachilli config.

![immagine](https://user-images.githubusercontent.com/519778/58081072-ac815e80-7bb4-11e9-9b65-eaae2d4f8fb0.png)

I didn't enable any settings:

![immagine](https://user-images.githubusercontent.com/519778/58081095-b86d2080-7bb4-11e9-8675-63832f018f2c.png)

**Comment by reinerotto** [comment]
My compile on ubutu 18.04.02 LTS, works, too, for a ZBT-WE826
Which target device do you use ?

**Comment by Helias** [comment]
target system: **MediaTek Railink MIPS**
subtarget: **MT7620**
target profile: **ASUS RT-AC51U**

**Comment by reinerotto** [comment]
You should try to compile in a fresh/clean build environment, I mean, after

git clone https://git.openwrt.org/openwrt/openwrt.git
git checkout v18.06.02
....

I used an ubuntu, on which I already did other openwrt builds before. Which means, I did
apt-get install build-essential git-core libncurses5-dev zlib1g-dev gawk flex quilt libssl-dev xsltproc libxml-parser-perl mercurial bzr ecj cvs unzip
already some time ago.

**Comment by reinerotto** [comment]
Strating compile for your ASUS. My ZBT also using MT7620A.

**Comment by reinerotto** [comment]
Compile done. No problem for me.

**Comment by Helias** [comment]
I did the same thing and I get that errors :S

**Comment by reinerotto** [comment]
Then the only explanation is some speciality in your ubuntu. I had similar effects on another server, running centos. Could not build any image; but same .config worked on my ubuntu.
Next try: New install of ubuntu etc.

**Comment by Helias** [comment]
Ok, I didn't solve it, but I understood that the problem is about my system libraries, probably with a fresh installation I will solve.
So I can close this.

**Comment by Abhijeet23081989** [comment]
Hello. i wanted to build coovachilli for openwrt with dhcpradius enabled.How do I do that??
And also after building it with dhcpradius enabled how to get the connected client hostname. I have searched for it all over and have come across this https://coova.github.io/mail-archive/chilli/2009-June/000779.html
& 
https://coova.github.io/mail-archive/chilli/2012-May/001943.html

it suggests to compile coovachilli with --enabled-dhcpradius option but what to do after that  I am clueless. Sorry for the rookie question, but  i am new to this. Please help.
