### ISSUE TITLE
coovachilli cannot install on centOS7

### ISSUE THREAD

**Issue by al2rex** [coova/coova-chilli#507]
i'm installing coovachilli on centos7 and when i run   **./configure --enable-miniportal --prefix=/tmp/foo** the terminal told me :

configure: error: in `/usr/src/coova-chilli-1.5':
configure: error: C++ compiler cannot create executables
See `config.log' for more details

**when i check config.log file this one show me the next one:**

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by coova-chilli configure 1.4, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --enable-miniportal --prefix=/tmp/foo

## --------- ##

hostname = localhost.localdomain
uname -m = x86_64
uname -r = 3.10.0-1062.9.1.el7.x86_64
uname -s = Linux
uname -v = #1 SMP Fri Dec 6 15:49:49 UTC 2019

/usr/bin/uname -p = x86_64
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/local/bin
PATH: /usr/bin
PATH: /usr/local/sbin
PATH: /usr/sbin
PATH: /home/al2rex/.local/bin
PATH: /home/al2rex/bin

## ----------- ##

configure:2876: checking for a BSD-compatible install
configure:2944: result: /usr/bin/install -c
configure:2955: checking whether build environment is sane
configure:3010: result: yes
configure:3161: checking for a thread-safe mkdir -p
configure:3200: result: /usr/bin/mkdir -p
configure:3207: checking for gawk
configure:3223: found /usr/bin/gawk
configure:3234: result: gawk
configure:3245: checking whether make sets $(MAKE)
configure:3267: result: yes
configure:3296: checking whether make supports nested variables
configure:3313: result: yes
configure:3503: checking for g++
configure:3533: result: no
configure:3503: checking for c++
configure:3533: result: no
configure:3503: checking for gpp
configure:3533: result: no
configure:3503: checking for aCC
configure:3533: result: no
configure:3503: checking for CC
configure:3533: result: no
configure:3503: checking for cxx
configure:3533: result: no
configure:3503: checking for cc++
configure:3533: result: no
configure:3503: checking for cl.exe
configure:3533: result: no
configure:3503: checking for FCC
configure:3533: result: no
configure:3503: checking for KCC
configure:3533: result: no
configure:3503: checking for RCC
configure:3533: result: no
configure:3503: checking for xlC_r
configure:3533: result: no
configure:3503: checking for xlC
configure:3533: result: no
configure:3557: checking for C++ compiler version
configure:3566: g++ --version >&5
./configure: line 3568: g++: command not found
configure:3577: $? = 127
configure:3566: g++ -v >&5
./configure: line 3568: g++: command not found
configure:3577: $? = 127
configure:3566: g++ -V >&5
./configure: line 3568: g++: command not found
configure:3577: $? = 127
configure:3566: g++ -qversion >&5
./configure: line 3568: g++: command not found
configure:3577: $? = 127
configure:3597: checking whether the C++ compiler works
configure:3619: g++    conftest.cpp  >&5
./configure: line 3621: g++: command not found
configure:3623: $? = 127
configure:3661: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "coova-chilli"
| #define PACKAGE_TARNAME "coova-chilli"
| #define PACKAGE_VERSION "1.4"
| #define PACKAGE_STRING "coova-chilli 1.4"
| #define PACKAGE_BUGREPORT "https://github.com/coova/coova-chilli/issues"
| #define PACKAGE_URL ""
| #define PACKAGE "coova-chilli"
| #define VERSION "1.4"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:3666: error: in `/usr/src/coova-chilli-1.5':
configure:3668: error: C++ compiler cannot create executables
See `config.log' for more details

## ---------------- ##

ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXCPP_set=
ac_cv_env_CXXCPP_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_set=
ac_cv_env_CXX_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/usr/bin/mkdir
ac_cv_prog_AWK=gawk
ac_cv_prog_make_make_set=yes
am_cv_make_support_nested_variables=yes

## ----------------- ##

ACLOCAL='${SHELL} /usr/src/coova-chilli-1.5/missing aclocal-1.14'
AMDEPBACKSLASH=''
AMDEP_FALSE=''
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='1'
AM_V='$(V)'
AR=''
AUTOCONF='${SHELL} /usr/src/coova-chilli-1.5/missing autoconf'
AUTOHEADER='${SHELL} /usr/src/coova-chilli-1.5/missing autoheader'
AUTOMAKE='${SHELL} /usr/src/coova-chilli-1.5/missing automake-1.14'
AWK='gawk'
CC=''
CCDEPMODE=''
CFLAGS=''
CPP=''
CPPFLAGS=''
CXX='g++'
CXXCPP=''
CXXDEPMODE=''
CXXFLAGS=''
CYGPATH_W='echo'
DEFS=''
DEPDIR=''
DLLTOOL=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
EXEEXT=''
FGREP=''
GREP=''
HAVE_LINUX_TPACKET_AUXDATA=''
HAVE_STRLCPY_FALSE=''
HAVE_STRLCPY_TRUE=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LD=''
LDFLAGS=''
LIBCURL=''
LIBJSON=''
LIBNETFILTER_QUEUE=''
LIBOBJS=''
LIBPCAP=''
LIBS=''
LIBSSL=''
LIBTOOL=''
LIPO=''
LN_S=''
LTLIBOBJS=''
MAKEINFO='${SHELL} /usr/src/coova-chilli-1.5/missing makeinfo'
MANIFEST_TOOL=''
MKDIR_P='/usr/bin/mkdir -p'
NM=''
NMEDIT=''
OBJDUMP=''
OBJEXT=''
OTOOL64=''
OTOOL=''
PACKAGE='coova-chilli'
PACKAGE_BUGREPORT='https://github.com/coova/coova-chilli/issues'
PACKAGE_NAME='coova-chilli'
PACKAGE_STRING='coova-chilli 1.4'
PACKAGE_TARNAME='coova-chilli'
PACKAGE_URL=''
PACKAGE_VERSION='1.4'
PATH_SEPARATOR=':'
RANLIB=''
SED=''
SET_MAKE=''
SHELL='/bin/sh'
STRIP=''
VERSION='1.4'
WITH_AUTHEDALLOWED_FALSE=''
WITH_AUTHEDALLOWED_TRUE=''
WITH_AVL_FALSE=''
WITH_AVL_TRUE=''
WITH_CHILLIPROXY_FALSE=''
WITH_CHILLIPROXY_TRUE=''
WITH_CHILLIQUERY_FALSE=''
WITH_CHILLIQUERY_TRUE=''
WITH_CHILLIRADSEC_FALSE=''
WITH_CHILLIRADSEC_TRUE=''
WITH_CHILLIREDIR_FALSE=''
WITH_CHILLIREDIR_TRUE=''
WITH_CHILLISCRIPT_FALSE=''
WITH_CHILLISCRIPT_TRUE=''
WITH_CLUSTER_FALSE=''
WITH_CLUSTER_TRUE=''
WITH_CONFIG_FALSE=''
WITH_CONFIG_TRUE=''
WITH_CURL_FALSE=''
WITH_CURL_TRUE=''
WITH_CYASSL_FALSE=''
WITH_CYASSL_TRUE=''
WITH_EAPOL_FALSE=''
WITH_EAPOL_TRUE=''
WITH_EWTAPI_FALSE=''
WITH_EWTAPI_TRUE=''
WITH_IEEE8023_FALSE=''
WITH_IEEE8023_TRUE=''
WITH_IPV6_FALSE=''
WITH_IPV6_TRUE=''
WITH_JSONLIB_FALSE=''
WITH_JSONLIB_TRUE=''
WITH_L2TP_PPP_FALSE=''
WITH_L2TP_PPP_TRUE=''
WITH_LOCATION_FALSE=''
WITH_LOCATION_TRUE=''
WITH_LOOKUP3_FALSE=''
WITH_LOOKUP3_TRUE=''
WITH_MATRIXSSL_CLI_FALSE=''
WITH_MATRIXSSL_CLI_TRUE=''
WITH_MATRIXSSL_FALSE=''
WITH_MATRIXSSL_TRUE=''
WITH_MDNS_FALSE=''
WITH_MDNS_TRUE=''
WITH_MINICONFIG_FALSE=''
WITH_MINICONFIG_TRUE=''
WITH_MINIPORTAL_FALSE=''
WITH_MINIPORTAL_TRUE=''
WITH_MODULES_FALSE=''
WITH_MODULES_TRUE=''
WITH_MULTILAN_FALSE=''
WITH_MULTILAN_TRUE=''
WITH_MULTIROUTE_FALSE=''
WITH_MULTIROUTE_TRUE=''
WITH_NETBIOS_FALSE=''
WITH_NETBIOS_TRUE=''
WITH_NETFILTER_COOVA_FALSE=''
WITH_NETFILTER_COOVA_TRUE=''
WITH_NETFILTER_QUEUE_FALSE=''
WITH_NETFILTER_QUEUE_TRUE=''
WITH_NETNAT_FALSE=''
WITH_NETNAT_TRUE=''
WITH_OPENSSL_FALSE=''
WITH_OPENSSL_TRUE=''
WITH_PATRICIA_FALSE=''
WITH_PATRICIA_TRUE=''
WITH_PCAP_FALSE=''
WITH_PCAP_TRUE=''
WITH_PPPOE_FALSE=''
WITH_PPPOE_TRUE=''
WITH_REDIRINJECT_FALSE=''
WITH_REDIRINJECT_TRUE=''
WITH_SFHASH_FALSE=''
WITH_SFHASH_TRUE=''
WITH_SSL_FALSE=''
WITH_SSL_TRUE=''
ac_ct_AR=''
ac_ct_CC=''
ac_ct_CXX=''
ac_ct_DUMPBIN=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__fastdepCXX_FALSE=''
am__fastdepCXX_TRUE=''
am__include=''
am__isrc=''
am__leading_dot='.'
am__nodep=''
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
bindir='${exec_prefix}/bin'
build=''
build_alias=''
build_cpu=''
build_os=''
build_vendor=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host=''
host_alias=''
host_cpu=''
host_os=''
host_vendor=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /usr/src/coova-chilli-1.5/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/tmp/foo'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "coova-chilli"
#define PACKAGE_TARNAME "coova-chilli"
#define PACKAGE_VERSION "1.4"
#define PACKAGE_STRING "coova-chilli 1.4"
#define PACKAGE_BUGREPORT "https://github.com/coova/coova-chilli/issues"
#define PACKAGE_URL ""
#define PACKAGE "coova-chilli"
#define VERSION "1.4"

configure: exit 77

**i've looked for  at everywhere but i cannot get any reply**

**Comment by sevan** [comment]
You don't have g++ installed.
