### ISSUE TITLE
Return of the Mac? Update me

### ISSUE THREAD

**Issue by gwisp** [coova/coova-chilli#508]
Hello All.
My Name is Rory, you may know me as GTWCMT from back in the day which Chilli Spot was new and was "underway".

I have been a little distant since 2007 following a long legal battle (which I won) and other issues arising therefore I haven't been "up with the project" and what had or has happened or what had not. Seems that the project exists in a number of formats and I see the "control" and "pay" has been used and is "money making" for some as a standalone service... pays the bills I guess.

**So as I recall..... and as we were....**

The zoning was required and we were looking at load balance and node routing as a back office to the wifi mesh. What has occurred in this respect? [correct pro type network mesh]

I had suggested that the "back office" and backhaul was moved from the Radius server so that the "network" management was a separate set. did this happen? [network and node management central]

Did we run out multi AP pingback and form any redundancy to failure and notice of failure? (Software had been provided for this by myself) [network monitoring]

Did the software install include tunnels for management and routing for multi AP and Backhaul?
[high speed network and multi point]

**Project background and my parts**
We were all chatting about slow internet and back then services from ISP were Slow and Costly.
We then came across the "sharing" of wireless and that a income could be generated from our own  web connections and selling this as a better service to others at a "community cost".

We needed firstly the "control" to the network as it was easy to put down AP and chain them to allow random people to connect, this posed issues.. so the captive log in portal was the first step. the second was the Radius and accounts, both for the user and the payment toward the costs.

Side to the project and part of this was my R&D into cost effective solutions to make a "better" network and "bigger network". As the network grows then there is a need for management. I had software that pingbacked and tested the network with a view of backhaul and node management with the routing and load balance. ( essential for QOS and fault finding).

The initial stages was a large 35Mile network where here ( UK_) there was a limit to TX power, so we increased RX and this gave good results in the ability to widen the network.

We looked at P2P tunnels so that we can connect a two zone from the AP so that we can run back haul across the network to load balance and manage the networks away from clients seamlessly.
The ideal was a load balance and routing system for the users and nodes on a number of web connects from backhauled AP connections. ( piped connections and routes) which included the setting up of a compression server for fast data bursts across the network and caches to slop slow downs and lessen the load on the web connects.

it was about this time that a company who I was providing services too decided not to pay and we got into court for about 18 months or so. I won the case and it turns out their new supplier was a little clueless and didn't know how to work or manage the system hence made false claims to the customer in respect of me, and well the rest is now history, however I never returned to the project due to "more serious" issues shortly after which I shall say was "at home".

G-WISP was packed away and has been for many years,  I had done the ground work and testing and all was good, I never did follow up and there was a gap, but the hardware has been taunting me when I move or go hunting for something and so I thought there seems like no time like now to go back to it.....

I did some hunting about to see what was what and found many playing off the "back office" provisions to others whom seem to want to do the same, particular the last mile solutions which are still needed world wide... I have seen the YouTube videos..

I need a update as I run out the "package" here as a small run, and if you recall I also did the SIP (telcom) which was attached, I did touch on this in 2011, but was halted illegally ( to give some explaination) and I put together the ITEC which was jointed from several projects and forks following the published works I did back between 2005 and 2007.

it seems odd looking back now at what we did then,  were are technically  still in there, but not as much as the massive impact and difference we were back then in the day.... ( I feel old just saying)…

Please update me in summary to the configuration before I start the installations and configuration to something that was not finished back 12 years ago.

**Comment by xewonder** [comment]
Not sure what you want m8....  all the documentation is out there... any problems you may have you can ask here and you may (hopefully) get an aswer.

**Comment by gwisp** [comment]
I was wondering how the platform (s) had changed, we used Squid, which needs to be updated as it doesn't handle security.
How far did load balance and backhauling take shape? (multi node routing with best effort)
