### ISSUE TITLE
Coova debuild issue in ubuntu20.04

### ISSUE THREAD

**Issue by albinjose08** [coova/coova-chilli#518]
Hi all,
Recently I've upgraded my Ubuntu 18.04 to 20.04 as a fresh installation. But while installing coovachilli 1.5, I'm getting below error in debuild section. I'm trying to set a Freeradius + Daloradius + Coovachilli combination.
Error-
cc1: all warnings being treated as errors
make[4]: *** [Makefile:968: chilli.lo] Error 1
make[4]: Leaving directory '/home/zaytech/Downloads/coova-chilli-1.5/src'
make[3]: *** [Makefile:1011: all-recursive] Error 1
make[3]: Leaving directory '/home/zaytech/Downloads/coova-chilli-1.5/src'
make[2]: *** [Makefile:417: all-recursive] Error 1
make[2]: Leaving directory '/home/zaytech/Downloads/coova-chilli-1.5'
make[1]: *** [Makefile:345: all] Error 2
make[1]: Leaving directory '/home/zaytech/Downloads/coova-chilli-1.5'
make: *** [debian/rules:35: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -b failed

Kindly support. 
Thanks for the help in advance..

**Comment by sevan** [comment]
this doesn't contain the actual error
