### ISSUE TITLE
Iphone makes double requests

### ISSUE THREAD

**Issue by Gidro76** [coova/coova-chilli#533]
I am using coova-chilli version 1.4-10 and openwrt version 19.07.7
When Iphone connects to the guest network and goes to the authorization page, it sends its data twice, which makes it impossible to authenticate the user on the network

**Comment by Gidro76** [comment]
Amendment for 1.5 is the same problem

**Comment by sevan** [comment]
Can you try the stock source from this repo rather than the openwrt package?

**Comment by Gidro76** [comment]
> Can you try the stock source from this repo rather than the openwrt package?

Do you suggest deploying just openwrt on linux OS?

**Comment by sevan** [comment]
No, I'm asking if can build & install v1.6 without from this repo & not install the openwrt coova package.

**Comment by Gidro76** [comment]
> Нет, я спрашиваю, могу ли я собрать и установить v1.6 без этого репо и не устанавливать пакет openwrt coova.
Ok, I'll try to replace the original code with version 1.6

**Comment by Gidro76** [comment]
![image](https://user-images.githubusercontent.com/54084407/143202845-8353c8ad-8ebb-4bfd-b332-0a734b804a87.png)
Sorry, I do not quite understand what then to integrate from this code into openwrt. The files are significantly different from mine
Or do you mean just unload the archive itself and install it via make?
