### ISSUE TITLE
Openwrt - seq_file: buggy .next function 0x81b600a8 did not update position index

### ISSUE THREAD

**Issue by xewonder** [coova/coova-chilli#544]
Good day,

Openwrt 21.02.2 with coova-chilli 1.6
Compiled with ENABLE_DEBUG ENABLE_ACCOUNTING_ONOFF ENABLE_BINSTATFILE ENABLE_CHILLIQUERY ENABLE_COA ENABLE_RADPROXY ENABLE_CHILLIREDIR ENABLE_DHCPRADIUS ENABLE_IEEE8021Q ENABLE_IPV6 ENABLE_JSON ENABLE_LEAKYBUCKET ENABLE_STATFILE ENABLE_TAP ENABLE_TCPRESET ENABLE_UAMANYIP ENABLE_UAMUIPORT HAVE_NETFILTER_COOVA HAVE_OPENSSL 

When staring chilli i keep getting this in the log:
[  509.196360] seq_file: buggy .next function 0x81b600a8 did not update position index
[  509.572810] seq_file: buggy .next function 0x81b600a8 did not update position index
[  509.951139] seq_file: buggy .next function 0x81b600a8 did not update position index
[  510.384319] seq_file: buggy .next function 0x81b600a8 did not update position index

it seems to work? but should i be worried about it?

Thanks

**Comment by xewonder** [comment]
everyone happy with this???


[  195.314480] *XT_UP NET IF is -192.168.182.0-
[  195.473730] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  196.793460] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  197.290396] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  198.862319] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  199.273236] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  200.357232] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  201.273324] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  202.276160] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  204.019913] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  205.052083] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  205.352493] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  206.308820] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  207.388553] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  208.190990] XT TC Rules Exit
[  208.237259] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  208.630216] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  209.011972] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  209.439049] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  209.928319] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  210.065099] MSD country code is  -202-
[  210.079916] MSD------Country Found
[  210.253755] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  210.656605] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  211.060426] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  211.492259] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  211.966642] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  212.350247] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  212.602124] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  212.629920] ****** Starting update control download
[  213.176062] MSD country code is  -202-
[  213.191216] MSD------Country Found
[  213.299213] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  213.486590] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  214.009823] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  214.477766] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  214.805607] CPSI GPS TZ XT_EXEC board.json cell chillistatus controlled dhcp.leases dnsmasq.d etc extroot hosts hs.conf.wlan0 lib lock log main.conf.wlan0 modemup msd overlay ready reboot resolv.conf resolv.conf.d roamer2 run shm spool state sysinfo tmp Sent Statistics
[  215.219447] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  215.603757] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  215.718950] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  216.132438] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  216.343876] ****** Update Script Executed
[  216.620624] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  217.087514] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  217.532099] seq_file: buggy .next function 0x81abe0a8 did not update position index
[  217.920725] seq_file: buggy .next function 0x81abe0a8 did not update position index

**Comment by xewonder** [comment]
hi.

this did not fix the problem

**Comment by xewonder** [comment]
any news on this?

**Comment by nzamps** [comment]
Well, it should have helped as it now matches the linux mainline xt_recent.c (which this module is based on). See https://github.com/torvalds/linux/blob/master/net/netfilter/xt_recent.c#L503

Are you sure you did a make clean etc ?

**Comment by nzamps** [comment]
That xt_coova.txt file you posted above doesn't have the patch added. You will need to do it manually as that change hasn't been merged yet.

**Comment by xewonder** [comment]
you are absolutely right!!

I was sure i made the changes... but on review, they were not there.. done it again and the issue is fixed!

Thank you!!
