### ISSUE TITLE
miniportal no response login. Openwrt 22.03.x

### ISSUE THREAD

**Issue by predators46** [coova/coova-chilli#557]
@neheb 
https://user-images.githubusercontent.com/31931530/185851206-f1dc0933-f3f0-4b8d-b6e0-ea2e09af1e83.mp4

**Comment by neheb** [comment]
maintainer is @teslamint . I don't use coova-chilli.

**Comment by predators46** [comment]
thank you for your answer. i ran into this on openwrt 22.03. no problem in openwrt 21.02

**Comment by predators46** [comment]
Fix
