### ISSUE TITLE
XT_COOVA not "called"?

### ISSUE THREAD

**Issue by xewonder** [coova/coova-chilli#560]
Hello

Coova-chilli is compiled with ENABLE_DEBUG ENABLE_ACCOUNTING_ONOFF ENABLE_BINSTATFILE ENABLE_CHILLIQUERY ENABLE_COA ENABLE_RADPROXY ENABLE_CHILLIREDIR ENABLE_DHCPRADIUS ENABLE_IEEE8021Q ENABLE_IPV6 ENABLE_JSON ENABLE_LEAKYBUCKET ENABLE_STATFILE ENABLE_TAP ENABLE_TCPRESET ENABLE_UAMANYIP ENABLE_UAMUIPORT HAVE_NETFILTER_COOVA HAVE_OPENSSL

On Ubuntu 20.04.5 LTS

i have kname=chilli in chilli.conf

up.sh reports chilli as $kname

but lsmod shows  xt_coova "used by 0"

Module                  Size  Used by
xt_coova               16384  0

and of course i get
iptables v1.8.4 (legacy): Couldn't load match `coova':No such file or directory

Whats the problem? 

Thank you

**Comment by xewonder** [comment]
further to my previous message, on openwrt i can see this:
[   73.502614] xt_coova: looking for chilli
[   73.510466] xt_coova: found chilli refcnt=4
[   73.518953] xt_coova: match ret=0
[   73.525600] xt_coova: looking for chilli
[   73.533518] xt_coova: found chilli refcnt=5
[   73.541801] xt_coova: match ret=0
[   73.548383] xt_coova: looking for chilli
[   73.556149] xt_coova: found chilli refcnt=6
[   73.564429] xt_coova: match ret=0
[   73.857124] xt_coova: looking for chilli
[   73.864959] xt_coova: found chilli refcnt=4
[   73.873287] xt_coova: match ret=0
[   73.879889] xt_coova: looking for chilli
[   73.887670] xt_coova: found chilli refcnt=5
[   73.895957] xt_coova: match ret=0
[   73.902510] xt_coova: looking for chilli
[   73.910281] xt_coova: found chilli refcnt=6
[   73.918565] xt_coova: match ret=0
[   76.427757] xt_coova: looking for chilli
[   76.435616] xt_coova: found chilli refcnt=4
[   76.443924] xt_coova: match ret=0
[   76.450513] xt_coova: looking for chilli
[   76.458287] xt_coova: found chilli refcnt=5
[   76.466746] xt_coova: match ret=0
[   76.473411] xt_coova: looking for chilli
[   76.481193] xt_coova: found chilli refcnt=6
[   76.489629] xt_coova: match ret=0
[   78.528999] xt_coova: looking for chilli
[   78.536889] xt_coova: found chilli refcnt=4
[   78.545289] xt_coova: match ret=0
[   78.551919] xt_coova: looking for chilli
[   78.559678] xt_coova: found chilli refcnt=5
[   78.567962] xt_coova: match ret=0
[   78.574525] xt_coova: looking for chilli
[   78.582289] xt_coova: found chilli refcnt=6
[   78.590565] xt_coova: match ret=0

on Ubuntu I only see 
xt_coova ready

My idea (and i may be wrong) is that xt_coova never starts up properly and therefore does not create the proper iptables entries..

Hence the error:

iptables v1.8.4 (legacy): Couldn't load match `coova':No such file or directory

**Comment by nzamps** [comment]
I don't have time at the moment to look closer at this but the hits you see are iptables rule matches - that is the only way to get those messages. You need to double-check your rules are correct and module name is specified correctly in each rule ("-m coova --name chilli").

**Comment by xewonder** [comment]
Just shows you how little i know but how determined I am!

for me the solution to 
iptables v1.8.4 (legacy): Couldn't load match `coova':No such file or directory

is to copy libxt_coova.so  to /usr/lib/x86_64-linux-gnu/xtables/libxt_coova.so

it looks like the coova-chilli install copies it to /usr/lib/xtables/libxt_coova.so (or my ./configure was screwed up)

Now the actual fun of getting it to work!
