### ISSUE TITLE
compatibility with PHP 8.1

### ISSUE THREAD

**Issue by mfaroukg** [coova/coova-chilli#566]
Have any one tested the coova-chilli on newest Ubuntu 22.04 with PHP 8.1?

I found any errors like:
1- Hasrel is giving CGI error Exception.
2- use name and password are not passed to the Freeradius.
3- No much people using this code since long time, any substitute ??

**Comment by esaaprillia** [comment]
what version of haserl are you using? i have tried php8 no problem

**Comment by mfaroukg** [comment]
Hi,

Here are the versions I Hve:

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.10
Release:	22.10
Codename:	kinetic

||/ Name           Version                 Architecture Description
+++-==============-=======================-============-===================================================================
ii  apache2        2.4.54-2ubuntu1.1       amd64        Apache HTTP Server
ii  haserl         0.9.36-1                amd64        CGI scripting program for embedded environments
ii  mysql-server   8.0.32-0ubuntu0.22.10.2 all          MySQL database server (metapackage depending on the latest version)
ii  php            2:8.1+92ubuntu1         all          server-side, HTML-embedded scripting language (default)

**Comment by predators46** [comment]
you can try haserl-0.9.35

**Comment by mfaroukg** [comment]
when I tried that, I found some issue with the package "lua"

haserl-0.9.35# ./configure --with-lua
.
.
.
configure: error: Package requirements (lua) were not met:

No package 'lua' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LUA_CFLAGS
and LUA_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

I tried many versions of the lua "5.2,5.3,5.4" every time can't be found

**Comment by predators46** [comment]
$5
https://gist.github.com/btbytes/769894

**Comment by mfaroukg** [comment]
Hi,
After I tried all versions of haserl and lua, still the configure command can't locate the lua application
--------------------------------------------------------------------------------
# dpkg -l | grep lua5
ii  liblua5.2-0:amd64                     5.2.4-2                                  amd64        Shared library for the Lua interpreter version 5.2
ii  liblua5.3-0:amd64                     5.3.6-1build1                            amd64        Shared library for the Lua interpreter version 5.3
ii  liblua5.4-0:amd64                     5.4.4-3                                  amd64        Shared library for the Lua interpreter version 5.4
-------------------------------------------------------------------------------
** Configuration summary for haserl 0.9.36:

	Building haserl with with lua disabled
	Building haserl with with bash-extensions disabled
	libs: 
-------------------------------------------------------------------------------
Trying with full path
-------------------------------------------------------------------------------
configure: error: Package requirements (/home/.../lua-5.4.4/src/lua) were not met:

No package '/home/.../lua-5.4.4/src/lua' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LUA_CFLAGS
and LUA_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
-------------------------------------------------------------------------------
# ll /home/.../lua-5.4.4/src/lua
-rwxr-xr-x 1 root root 308K Feb 12 23:54 /home/.../lua-5.4.4/src/lua*
-------------------------------------------------------------------------------
when I install the haserl direct using apt it installs lua5.2 without a problem.

The password page behavior shows refresh ever time I enter the user/password. I think the php8.1 not compatible with the haserl and lua and coova-chilli php codes

**Comment by mfaroukg** [comment]
Still the issue exist, any one have good knowledge of how it works with this PHP and why not passing the username and password to the freeradius?

**Comment by mfaroukg** [comment]
I  downgraded my OS to Ubuntu focal and it worked

**Comment by mfaroukg** [comment]
will try again when Ubuntu/PHP worked stable
