### ISSUE TITLE
Error relocating /lib//libchilli.so.0: __fxstat: symbol not found

### ISSUE THREAD

**Issue by yangliu0606** [coova/coova-chilli#573]
After I import the compiled chilli files, libbstring.so.0 and libchilli.so.0 files to the device, I try to start the chilli process, but this error is reported.

**Comment by sevan** [comment]
You may have a newer version of glibc on your build system than your target device?

**Comment by yangliu0606** [comment]
configure: error: expected an absolute directory name for --prefix: ./coovachilli
After the source code is compiled successfully, I want to move the compiled file package to another path (for example, --prefix=/A/B/chilli) and copy the chilli file to /C/D/chilli. However, a file path error is reported when you try to run the file after copying the file. I'd like to ask if I can configure relative path compilation?
