### ISSUE TITLE
Compile Error on OpenWrt json_object

### ISSUE THREAD

**Issue by edy-c** [coova/coova-chilli#64]
Hi,

compiling Coova Chilli on OpenWrt commit b7384ce55606c2a673c96e6986e1f72a8927671d produces the following errors:

_uClibc-0.9.33.2/coova-chilli-1.3.1.3/bstring/.libs/libbstring.so ../bstring/.libs/libbstring.so -lrt
./.libs/libchilli.so: undefined reference to `json_object_to_json_string'
./.libs/libchilli.so: undefined reference to `json_object_new_string'
./.libs/libchilli.so: undefined reference to `json_object_put'
collect2: error: ld returned 1 exit status

commit b7bd125beb4652a58001b667c4c6ce6e9c1b6459 is fine, no errors.

Thanks in advance

Edy

**Comment by pinkra** [comment]
You have to add --enable-libjson when running configure.

**Comment by edy-c** [comment]
Thanks,

with --enable-libjson compile is fine, no errors.
