### ISSUE TITLE
Error during compilation on OpenWRT

### ISSUE THREAD

**Issue by Spomky** [coova/coova-chilli#72]
Hi,

I have the following error when I try to build coova-chilli using OpenWRT buildroot:
```sh
Makefile.am: error: required file './README' not found
```

This file were removed by commit 11b1d7e1394f91a9553589eb27f2f96b2d217305

@pinkra Is it possible to restore this file?

**Comment by sevan** [comment]
This was a symlink to README.md to avoid duplication/having to maintain seperate files. You can just set the symlink until the issue is addressed in the repo.

**Comment by matahr** [comment]
in Ubuntu, there is another error "config.status: error: cannot find input file: `Makefile.in'"

**Comment by Spomky** [comment]
Thanks @sevan 

On [Stackoverflow](http://stackoverflow.com/questions/15013672/use-autotools-with-readme-md), I see that we can avoid to create this symlink during compilation by adding an option in `configure.ac` or `Makefile.am`.
Maybe this way is a more elegant solution to solve this issue.

**Comment by Spomky** [comment]
For those interested, I created my own patch:
```patch
--- a/Makefile.am
+++ b/Makefile.am
@@ -1,4 +1,5 @@
 ## Process this file with automake to produce Makefile.in
+AUTOMAKE_OPTIONS = foreign
 ACLOCAL_AMFLAGS = -I m4
 SUBDIRS = bstring 
 EXTRA_DIST = CREDITS LICENSE acsite.m4

```

If you agree, I let this issue opened until this patch is fully integrated into this project or the OpenWRT package.

**Comment by sevan** [comment]
But that has a bigger scope of impact than just ignoring the presence of README

**Comment by Spomky** [comment]
That's right. But as this option is already used in [src/Makefile.am#L1](https://github.com/coova/coova-chilli/blob/master/src/Makefile.am#L1) I thought it will not really impact the compilation.
I removed my patch and I added a simple command in the Makefile of my local env to create the symlink:
```
define Build/Prepare
$(call Build/Prepare/Default)
	( cd $(PKG_BUILD_DIR) ; \
		ln -s README.md README ; \
		[ -f ./configure ] || { \
			./bootstrap ; \
		} \
	)
endef
```

Works fine too.

**Comment by sevan** [comment]
Committed a fix to resolve the issue so out of the box a user doesn't need to work around anything, please confirm the issue is resolved for you.

**Comment by sevan** [comment]
@matahr even after re-running the bootstrap script?

**Comment by matahr** [comment]
| @matahr even after re-running the bootstrap script?

last commit, resolved the issue

**Comment by Spomky** [comment]
OK, I confirm it works fine now.
Thank you.
