### ISSUE TITLE
generate more unique session id

### ISSUE THREAD

**Issue by gareth41** [coova/coova-chilli#80]
I'm testing chilli in a backpackers hostel here in Auckland, getting around 100 logins every day.  Occasionally though we get duplicate session id's appear in the mysql radacct table, this seems to happen at-least once every 2 - 3 days.  Does anyone know the chilli source file used to generate the session id?

**Comment by nzamps** [comment]
Take a look at set_sessionid in chilli.c and mainclock_rt - do you have time set with ntp ?  

Also in Auckland! :)

**Comment by gufmar** [comment]
according to http://freeradius.org/radiusd/man/rlm_acct_unique.txt it's not uncommon that some NAS does not provide really unique `Acct-session-id` . So this rlm_acct_unique module should create an unique `Acct-Unique-Session-Id` 
Looking at our 3,4 million accounting records recorded in the past 5 days from around 500 NAS-devices we see several hundred duplicate Acct-session-id's coming from the same NAS device.
Thanks to the mentioned module the Acct-unique-session-id's  are "much more" unique. But not really 100% ... not even for the same NAS.
As all our hotspot locations have unique DHCP-ranges we added the `Framed-IP-Address` to the table index to solve this problem.
