### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Spomky** [coova/coova-chilli#83]
I found three sections where `realloc` is not used correctly:
- [src/cmdline.mini.c#L117](https://github.com/coova/coova-chilli/blob/master/src/cmdline.mini.c#L117)
- [src/garden.c#L236](https://github.com/coova/coova-chilli/blob/master/src/garden.c#L236)
- [src/garden.c#L287](https://github.com/coova/coova-chilli/blob/master/src/garden.c#L287)

If realloc fails, you will loose memory in the old pointer because it has been reassigned to `null`.
You should write something like that:

``` c
//Store the result in a temporary pointer
char **tmp = (char **)realloc(lp, *given * sizeof(char *));

if (tmp == NULL) {
    //In case of failure, do want you want (syslog, exception...).
} else {
    //In case of success, you can reassign the pointer
    lp = tmp;
}
```

**Comment by sevan** [comment]
Thanks for the heads up, will look at this in the next week
