### ISSUE TITLE
NIC ip address is removed on start, only when cable is unplugged

### ISSUE THREAD

**Issue by wirelessmundi** [coova/coova-chilli#88]
If the dhcpif NIC has no cable plugged-in, coova-chilli removes it's ip address when started, with the message: "removing ip address from ethX".

It could mess up system routes and cause some issues with other services using that ip address. Also when you stop coova-chilli, one can never know if the previous ip address will be there or not, because it depends if the cable was plugged-in at the time coova-chilli was started!

Is there any reason for this very specific behavior? If not, would it be fine to remove it or make it consistent (either never remove ip, or always remove ip whether cable is plugged-in or not)?

I located the issue on function "net_open" of src/net.c.

**Comment by sevan** [comment]
Can you try the latest release, this may be resolved now as per entry in release notes.

By the way, there is now [a mailing list for questions such as these](https://www.brightonchilli.org.uk/mailman/listinfo/coovachilli), the issues section will be used solely for bug reports in code from now on, can I ask you to subscribe & take the discussion there (give it a few days as the system is freshly setup without any subscribers at the moment).
