### ISSUE TITLE
Is there anywifi to change MAC format

### ISSUE THREAD

**Issue by forgaoqiang** [coova/coova-chilli#92]
I reviewed many other NAS , eg. mikrotik,  m0n0 linux ,they can defined the mac format as:
`00:11:22:33:44:55`
`00-11-22-33-44-55`
`0011.2233.4455`
`upper-case hex`
`lower-case hex`

Is there any way coovachilli do this ?

**Comment by sevan** [comment]
Hi,
There is now [a mailing list for questions such as these](https://www.brightonchilli.org.uk/mailman/listinfo/coovachilli), the issues section will be used solely for bug reports in code from now on, can I ask you to subscribe & take the discussion there (give it a few days as the system is freshly setup without any subscribers at the moment).
