### ISSUE TITLE
CoovaChilli - Content Injection

### ISSUE THREAD

**Issue by ejherran** [coova/coova-chilli#93]
Hello.
I'm trying to enable the injection of content, but after several days of searching, I failed to find any documentation on the subject (Except some post on linkedin).

They would be so kind as to tell me that steps to enable this feature (A sample configuration if possible).

Thank you.

**Comment by m4xw** [comment]
You should try to combine it with Squid (it has a example Plugin).

But you won't be able to alter SSL connections unless you use something like SSLSplit

**Comment by ejherran** [comment]
Thank you. I am currently testing with proxy. I would appreciate any additional recommendation or a sample configuration.
Thanks, again.

**Comment by m4xw** [comment]
I think it was called eCap or iCap.

You have to google it yourself, it was some years ago for me.

There are some example plugins out there but I'am not sure, maybe there are better solutions nowadays!

Gl

**Comment by sevan** [comment]
Hi,
There is now [a mailing list for questions such as these](https://www.brightonchilli.org.uk/mailman/listinfo/coovachilli), the issues section will be used solely for bug reports in code from now on, can I ask you to subscribe & take the discussion there (give it a few days as the system is freshly setup without any subscribers at the moment).
