### ISSUE TITLE
Compilation fails in arm architecture (raspberry jessie)

### ISSUE THREAD

**Issue by mcassisa** [coova/coova-chilli#94]
dpkg-buildpackage of coova-chilli_1.3.0.tar.gz
fails complaining  main-opt.c:781:29: error: ‘ptr’ may be used uninitialized in this function
[-Werror=maybe-uninitialized]

The command fails in jessie, not in wheezy.
Solved by changing line 781 from
      char *tok, *str, *ptr;
to:
      char *tok, *str, *ptr = NULL;

**Comment by ioannisky** [comment]
Hi!
The reason for the error is that the compiler treats warnings as errors. Its not an arm specific issue.
I think if you do an: 
export CFLAGS="-Wno-error"
before running the ./configure <whatever settings you have>
and then run make it should be fine.
Not sure how it works with dpkg-buildpackage.

**Comment by Polioman** [comment]
It works with the export. Make and make install are OK.

I still have an issue with tun0 but it might be due to Network manager. I need network manager to have an internet access trough LTE usb modem. Since tun0 is not in /etc/network/interfaces network manager try to manage this interface even if chilli is able to do it.

**Comment by Polioman** [comment]
In fact, network manager is trying to manage an interface which is not up because chilli didn't start on boot (don't know why for now).

**Comment by sevan** [comment]
It's no longer needed to export your CFLAGS with -Wno-error, a commit earlier initialised those pointers to 0.

**Comment by sevan** [comment]
@Polioman can you try again from the latest git sources (without adjusting CFLAGS)

**Comment by Polioman** [comment]
Hi,

It's late but I used a more recent version of git sources than in November and it worked well.

Thanks.

**Comment by anselanza** [comment]
I'm using what I assume is the latest version (1.3.0) and I still need to set the CFLAGS to get this to build on a Banana Pi with Debian 8.
